/* eslint-disable prettier/prettier */
export default {
   username: 'Username',
   password: 'Password',
   Server: 'Server IP',
   login: 'Login',
   welcome: 'Welcome',
   change_language: 'Change language',
   Tabs: 'Home',

   Lista_instalaciones: 'Installations',
   Maintenance: 'Maintenance',
   DetallesInstalacion: 'Installation details',
   Grabar: 'Record',
   EstadoStore: 'Store status',
   Nodata: 'No data',
   DosimacRegistration: 'Registration',
   NewDmMaternity: 'New Dosimac maternity',
   DosimacG: 'Dosimac-G',
   DosimacI: 'Dosimac-I',
   UpdDmMaternity: 'Update Dosimac maternity',
   NewDmGestation: 'New Dosimac gestation',
   UpdDmGestation: 'Update Dosimac gestation',
   StartScan: 'Search DOSIMAC devices',
   DosimacList: 'DOSIMAC devices',
   PressToScan: 'Press',
   DosimacSetup: 'Configuration',
   TestoPresioneAlta: 'Press the button to search devices',
   Instalación_seleccionada: 'Selected installation',
   NoInstalacionSeleccionada: 'No installation selected',
   BorrarGranja: 'Delete farm',
   Deseaborrarlagranja: 'Do you want to delete the farm?',
   Guardar: 'Save',
   Cancelar: 'Cancel',
   Aceptar: 'Accept',
   NombreGranja: 'Farm name',
   Localidad: 'Location',
   Provincia: 'Province',
   NombreWifi: 'Wifi SSID',
   PasswordWifi: 'Wifi password',
   No_hay_dispositivos: 'No devices',
   Aviso: 'Notice',
   SearchingDevices: 'Searching devices...',
   NoSePuedeBorrarGranja: 'You cannot delete a new farm',
   settings: 'Settings',
   softwareVersion: 'Software version',
   numeroCoral: 'Pen number',
   numeroMaquina: 'Machine number',
   Enviar: 'Send',
   Salir: 'Exit',
   Informacion: 'Information',
   InicioConfiguracion: 'Starting connection',
   ConfiguracionWifi: 'Configuring...',
   ConfiguracionRealizada: '*Configuration completed*',
   ErrorConfiguracion: '*Configuration error*',
   CapturaTagCorral: 'Capture pen tag',
   CorralTag: 'Corral tag',
   versionUint16: 'This device version only supports pens up to 65000',
   versionUint32: 'This device version supports pens up to 4000000000',
   EnvioConfiguracion: 'Sending configuration',
   NumeroCorral: 'Pen number',
   Corralnovalido: 'Invalid pen',
   Númeromáquinanovalido: 'Invalid machine number',
   configuracuarIntalacion: 'You must configure at least one installation',

   gestacionConfig_screenTitle: "Gestation Settings",
   gestacionConfig_chooseOptionTitle: "Choose an option",
   gestacionConfig_chooseOptionDescription: "Define the workflow before starting with the reader.",

   gestacionConfig_entry: "Entry",
   gestacionConfig_exit: "Exit",
   gestacionConfig_reading: "Reading",
   gestacionConfig_search: "Search",

   gestacionConfig_entryParamsTitle: "Entry parameters",
   gestacionConfig_exitParamsTitle: "Exit parameters",
   gestacionConfig_entryParamsDescription: "Select the pen and the workflow behavior.",
   gestacionConfig_exitParamsDescription: "Configure the exit workflow behavior.",

   gestacionConfig_corralLabel: "Pen",
   gestacionConfig_corralPlaceholder: "Ex: 1",
   gestacionConfig_corralRequired: "Enter the pen to continue.",

   gestacionConfig_detectUnknownTitle: "Identify unknown animals",
   gestacionConfig_detectUnknownDescription: "When you read an unidentified animal, you will be able to assign it an ID",

   gestacionConfig_confirmTitle: "Confirm submission",
   gestacionConfig_confirmDescription: "It will ask for confirmation before sending the records.",

   gestacionConfig_animalSearchTitle: "Animal search",
   gestacionConfig_animalSearchDescription: "Choose whether you want to search by ear tag or ID.",
   gestacionConfig_searchByCrotal: "By ear tag",
   gestacionConfig_searchById: "By ID",
   gestacionConfig_manual: "Manual",
   gestacionConfig_withSword: "With reader",

   gestacionConfig_crotalLabelSearch: "Ear tag",
   gestacionConfig_idLabelSearch: "ID",
   gestacionConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
   gestacionConfig_idPlaceholderSearch: "Ex: A13",
   gestacionConfig_crotalRequiredSearch: "Enter an ear tag to continue.",
   gestacionConfig_idRequiredSearch: "Enter an ID to continue.",

   gestacionConfig_searchWithSwordHelp: "When you continue, the reader will scan on this screen and the animal will be searched using that ear tag.",

   gestacionConfig_readingSword: "Reading reader...",
   gestacionConfig_waitingMatch: "Waiting for match",
   gestacionConfig_searchingAnimal: "Searching animal...",

   gestacionConfig_readingSwordDescription: "Bring the ear tag close to the reader to identify the animal.",
   gestacionConfig_waitingMatchDescription: "Animal found. Now bring ear tag {{crotal}} close to the reader to confirm the match.",
   gestacionConfig_searchingAnimalDescription: "Checking animal information in the backend.",

   gestacionConfig_awrDisconnectedTitle: "AWR not connected",
   gestacionConfig_awrSavedDescription: "You have saved readers. Tap to select one.",
   gestacionConfig_awrNotSavedDescription: "You do not have any saved readers. Tap to scan one.",

   gestacionConfig_scan: "Scan",
   gestacionConfig_continue: "Continue",

   gestacionConfig_alerts_error: "Error",
   gestacionConfig_alerts_networkError: "Network error",
   gestacionConfig_alerts_networkErrorMessage: "Could not connect to the server.",
   gestacionConfig_alerts_backendNoValidCrotal: "The backend did not return a valid ear tag for comparison.",
   gestacionConfig_alerts_awrNotConnected: "AWR not connected",
   gestacionConfig_alerts_connectSwordBeforeContinue: "Connect a reader before continuing.",
   gestacionConfig_alerts_couldNotStartReading: "Could not start reading with the reader.",

   gestacionConfig_alerts_missingData: "Missing data",
   gestacionConfig_alerts_writeCrotalToSearch: "Enter an ear tag to search.",
   gestacionConfig_alerts_writeIdToSearch: "Enter an ID to search.",

   gestacionConfig_alerts_notFound: "Not found",
   gestacionConfig_alerts_animalNotFoundByCrotal: "No animal exists with that ear tag.",
   gestacionConfig_alerts_animalNotFoundById: "No animal exists with that ID.",

   gestacionConfig_alerts_warning: "Warning",
   gestacionConfig_alerts_searchError: "Search error",

   maternidadConfig_screenTitle: "Maternity Settings",
   maternidadConfig_chooseOptionTitle: "Choose an option",
   maternidadConfig_chooseOptionDescription: "Set the workflow before starting the reader.",
   maternidadConfig_entry: "Entry",
   maternidadConfig_exit: "Exit",
   maternidadConfig_reading: "Reading",
   maternidadConfig_search: "Search",
   maternidadConfig_entryParamsTitle: "Entry parameters",
   maternidadConfig_exitParamsTitle: "Exit parameters",
   maternidadConfig_entryParamsDescription: "Select the pen and workflow behavior.",
   maternidadConfig_exitParamsDescription: "Configure the exit workflow behavior.",
   maternidadConfig_corralLabel: "Pen",
   maternidadConfig_corralPlaceholder: "Ex: 1",
   maternidadConfig_corralRequired: "Enter the pen to continue.",
   maternidadConfig_detectUnknownTitle: "Identify unknown animals",
   maternidadConfig_detectUnknownDescription: "When you read an unidentified animal, you will be able to assign it an ID",
   maternidadConfig_confirmTitle: "Confirm sending",
   maternidadConfig_confirmDescription: "It will ask for confirmation before sending each record.",
   maternidadConfig_animalSearchTitle: "Animal search",
   maternidadConfig_animalSearchDescription: "Choose whether you want to search by ear tag or ID.",
   maternidadConfig_searchByCrotal: "By ear tag",
   maternidadConfig_searchById: "By ID",
   maternidadConfig_manual: "Manual",
   maternidadConfig_withSword: "With reader",
   maternidadConfig_crotalLabelSearch: "Ear tag",
   maternidadConfig_idLabelSearch: "ID",
   maternidadConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
   maternidadConfig_idPlaceholderSearch: "Ex: A13",
   maternidadConfig_crotalRequiredSearch: "Enter an ear tag to continue.",
   maternidadConfig_idRequiredSearch: "Enter an ID to continue.",
   maternidadConfig_searchWithSwordHelp: "When you tap Scan, the reader will be used on this screen and the animal will be searched by that ear tag.",
   maternidadConfig_readingSword: "Reading reader...",
   maternidadConfig_waitingMatch: "Waiting for match",
   maternidadConfig_searchingAnimal: "Searching animal...",
   maternidadConfig_readingSwordDescription: "Bring the ear tag close to the reader to identify the animal.",
   maternidadConfig_waitingMatchDescription: "Animal found. Now bring ear tag {{crotal}} close to the reader to confirm the match.",
   maternidadConfig_searchingAnimalDescription: "Checking animal information in the backend.",
   maternidadConfig_awrDisconnectedTitle: "AWR not connected",
   maternidadConfig_awrSavedDescription: "You have saved AWR devices. Tap to select one.",
   maternidadConfig_awrNotSavedDescription: "You do not have any saved AWR devices. Tap to scan one.",
   maternidadConfig_scan: "Scan",
   maternidadConfig_continue: "Continue",
   maternidadConfig_alert_error: "Error",
   maternidadConfig_alert_invalidBackendCrotal: "The backend did not return a valid ear tag to compare.",
   maternidadConfig_alert_awrNotConnected: "AWR not connected",
   maternidadConfig_alert_connectSwordBeforeContinue: "Connect a reader before continuing.",
   maternidadConfig_alert_couldNotStartReading: "Could not start reading with the reader.",
   maternidadConfig_alert_missingData: "Missing data",
   maternidadConfig_alert_writeCrotalToSearch: "Enter an ear tag to search.",
   maternidadConfig_alert_writeIdToSearch: "Enter an ID to search.",
   maternidadConfig_alert_notFound: "Not found",
   maternidadConfig_alert_noAnimalWithCrotal: "There is no animal with that ear tag.",
   maternidadConfig_alert_noAnimalWithId: "There is no animal with that ID.",
   maternidadConfig_alert_warning: "Warning",
   maternidadConfig_alert_searchError: "Search error",
   maternidadConfig_alert_networkError: "Network error",
   maternidadConfig_alert_networkErrorMessage: "Could not connect to the server.",


};