export default {
    username: 'Utente',
    password: 'Password',
    login: 'Accedi',
    welcome: 'Benvenuto',
    change_language: 'Cambia lingua',
    Tabs: 'Home',

    Lista_instalaciones: 'Installazioni',
    Maintenance: 'Manutenzione',
    DetallesInstalacion: 'Dettagli installazione',
    Grabar: 'Salva',
    EstadoStore: 'Stato store',
    Nodata: 'Nessun dato',
    DosimacRegistration: 'Registrazione',
    NewDmMaternity: 'Nuovo Dosimac maternità',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Aggiorna Dosimac maternità',
    NewDmGestation: 'Nuovo Dosimac gestazione',
    UpdDmGestation: 'Aggiorna Dosimac gestazione',
    StartScan: 'Cerca dispositivi DOSIMAC',
    DosimacList: 'Dispositivi DOSIMAC',
    PressToScan: 'Premi',
    DosimacSetup: 'Configurazione',
    TestoPresioneAlta: 'Premi il pulsante per cercare i dispositivi',
    Instalación_seleccionada: 'Installazione selezionata',
    NoInstalacionSeleccionada: 'Nessuna installazione selezionata',
    BorrarGranja: 'Elimina fattoria',
    Deseaborrarlagranja: 'Vuoi eliminare la fattoria?',
    Guardar: 'Salva',
    Cancelar: 'Annulla',
    Aceptar: 'Accetta',
    NombreGranja: 'Nome della fattoria',
    Localidad: 'Località',
    Provincia: 'Provincia',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Password Wifi',
    No_hay_dispositivos: 'Nessun dispositivo',
    Aviso: 'Avviso',
    SearchingDevices: 'Ricerca dispositivi...',
    NoSePuedeBorrarGranja: 'Non è possibile eliminare una nuova fattoria',
    settings: 'Impostazioni',
    softwareVersion: 'Versione software',
    numeroCoral: 'Numero del recinto',
    numeroMaquina: 'Numero della macchina',
    Enviar: 'Invia',
    Salir: 'Esci',
    Informacion: 'Informazioni',

    InicioConfiguracion: "Avvio connessione",
    ConfiguracionWifi: "Configurazione in corso...",
    ConfiguracionRealizada: "*Configurazione completata*",
    ErrorConfiguracion: "*Errore di configurazione*",
    CapturaTagCorral: "Acquisisci tag del recinto",
    CorralTag: "Tag del recinto",
    versionUint16: "Questa versione del dispositivo supporta recinti solo fino a 65000",
    versionUint32: "Questa versione del dispositivo supporta recinti fino a 4000000000",
    EnvioConfiguracion: "Invio della configurazione",
    NumeroCorral: "Numero del recinto",
    NumeroMaquina: "Numero macchina",
    Corralnovalido: "Recinto non valido",
    Númeromáquinanovalido: "Numero macchina non valido",
    configuarIntalacion: "Devi configurare almeno un'installazione",

    gestacionConfig_screenTitle: "Configurazione Gestazione",
    gestacionConfig_chooseOptionTitle: "Scegli un'opzione",
    gestacionConfig_chooseOptionDescription: "Definisci il flusso prima di iniziare con il lettore.",

    gestacionConfig_entry: "Entrata",
    gestacionConfig_exit: "Uscita",
    gestacionConfig_reading: "Lettura",
    gestacionConfig_search: "Ricerca",

    gestacionConfig_entryParamsTitle: "Parametri di entrata",
    gestacionConfig_exitParamsTitle: "Parametri di uscita",
    gestacionConfig_entryParamsDescription: "Seleziona il recinto e il comportamento del flusso.",
    gestacionConfig_exitParamsDescription: "Configura il comportamento del flusso di uscita.",

    gestacionConfig_corralLabel: "Recinto",
    gestacionConfig_corralPlaceholder: "Es: 1",
    gestacionConfig_corralRequired: "Inserisci il recinto per continuare.",

    gestacionConfig_detectUnknownTitle: "Identificare animali sconosciuti",
    gestacionConfig_detectUnknownDescription: "Quando leggerai un animale non identificato, potrai assegnargli un ID",

    gestacionConfig_confirmTitle: "Confermare invio",
    gestacionConfig_confirmDescription: "Chiederà conferma prima di inviare i registri.",

    gestacionConfig_animalSearchTitle: "Ricerca animale",
    gestacionConfig_animalSearchDescription: "Scegli se vuoi cercare per crotale o per ID.",
    gestacionConfig_searchByCrotal: "Per crotale",
    gestacionConfig_searchById: "Per ID",
    gestacionConfig_manual: "Manuale",
    gestacionConfig_withSword: "Con spada",

    gestacionConfig_crotalLabelSearch: "Crotale",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Es: 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Es: A13",
    gestacionConfig_crotalRequiredSearch: "Inserisci un crotale per continuare.",
    gestacionConfig_idRequiredSearch: "Inserisci un ID per continuare.",

    gestacionConfig_searchWithSwordHelp: "Continuando, la spada verrà letta in questa schermata e l'animale verrà cercato con quel crotale.",

    gestacionConfig_readingSword: "Lettura spada...",
    gestacionConfig_waitingMatch: "In attesa di corrispondenza",
    gestacionConfig_searchingAnimal: "Ricerca animale...",

    gestacionConfig_readingSwordDescription: "Avvicina il crotale al lettore per identificare l'animale.",
    gestacionConfig_waitingMatchDescription: "Animale individuato. Ora avvicina alla spada il crotale {{crotal}} per confermare la corrispondenza.",
    gestacionConfig_searchingAnimalDescription: "Consultazione delle informazioni dell'animale nel backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR non connesso",
    gestacionConfig_awrSavedDescription: "Hai spade salvate. Premi per selezionarne una.",
    gestacionConfig_awrNotSavedDescription: "Non hai spade salvate. Premi per scansionarne una.",

    gestacionConfig_scan: "Scansiona",
    gestacionConfig_continue: "Continua",

    gestacionConfig_alerts_error: "Errore",
    gestacionConfig_alerts_networkError: "Errore di rete",
    gestacionConfig_alerts_networkErrorMessage: "Impossibile connettersi al server.",
    gestacionConfig_alerts_backendNoValidCrotal: "Il backend non ha restituito un crotale valido da confrontare.",
    gestacionConfig_alerts_awrNotConnected: "AWR non connesso",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Collega una spada prima di continuare.",
    gestacionConfig_alerts_couldNotStartReading: "Non è stato possibile avviare la lettura con la spada.",

    gestacionConfig_alerts_missingData: "Dato mancante",
    gestacionConfig_alerts_writeCrotalToSearch: "Inserisci un crotale da cercare.",
    gestacionConfig_alerts_writeIdToSearch: "Inserisci un ID da cercare.",

    gestacionConfig_alerts_notFound: "Non trovato",
    gestacionConfig_alerts_animalNotFoundByCrotal: "Non esiste alcun animale con questo crotale.",
    gestacionConfig_alerts_animalNotFoundById: "Non esiste alcun animale con questo ID.",

    gestacionConfig_alerts_warning: "Avviso",
    gestacionConfig_alerts_searchError: "Errore di ricerca",

    maternidadConfig_screenTitle: "Configurazione Maternità",
    maternidadConfig_chooseOptionTitle: "Scegli un'opzione",
    maternidadConfig_chooseOptionDescription: "Definisci il flusso prima di iniziare con il lettore.",
    maternidadConfig_entry: "Entrata",
    maternidadConfig_exit: "Uscita",
    maternidadConfig_reading: "Lettura",
    maternidadConfig_search: "Ricerca",
    maternidadConfig_entryParamsTitle: "Parametri di entrata",
    maternidadConfig_exitParamsTitle: "Parametri di uscita",
    maternidadConfig_entryParamsDescription: "Seleziona il recinto e il comportamento del flusso.",
    maternidadConfig_exitParamsDescription: "Configura il comportamento del flusso di uscita.",
    maternidadConfig_corralLabel: "Recinto",
    maternidadConfig_corralPlaceholder: "Es: 1",
    maternidadConfig_corralRequired: "Inserisci il recinto per continuare.",
    maternidadConfig_detectUnknownTitle: "Identificare animali sconosciuti",
    maternidadConfig_detectUnknownDescription: "Quando leggi un animale non identificato, potrai assegnargli un ID",
    maternidadConfig_confirmTitle: "Conferma invio",
    maternidadConfig_confirmDescription: "Chiederà conferma prima di inviare ogni registrazione.",
    maternidadConfig_animalSearchTitle: "Ricerca animale",
    maternidadConfig_animalSearchDescription: "Scegli se vuoi cercare per crotale o per ID.",
    maternidadConfig_searchByCrotal: "Per crotale",
    maternidadConfig_searchById: "Per ID",
    maternidadConfig_manual: "Manuale",
    maternidadConfig_withSword: "Con lettore",
    maternidadConfig_crotalLabelSearch: "Crotale",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Es: 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Es: A13",
    maternidadConfig_crotalRequiredSearch: "Inserisci un crotale per continuare.",
    maternidadConfig_idRequiredSearch: "Inserisci un ID per continuare.",
    maternidadConfig_searchWithSwordHelp: "Premendo Scansiona, il lettore verrà usato in questa schermata e l'animale verrà cercato con quel crotale.",
    maternidadConfig_readingSword: "Lettura del lettore...",
    maternidadConfig_waitingMatch: "In attesa di corrispondenza",
    maternidadConfig_searchingAnimal: "Ricerca animale...",
    maternidadConfig_readingSwordDescription: "Avvicina il crotale al lettore per identificare l'animale.",
    maternidadConfig_waitingMatchDescription: "Animale trovato. Ora avvicina al lettore il crotale {{crotal}} per confermare la corrispondenza.",
    maternidadConfig_searchingAnimalDescription: "Consultazione delle informazioni dell'animale nel backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR non connesso",
    maternidadConfig_awrSavedDescription: "Hai AWR salvati. Premi per selezionarne uno.",
    maternidadConfig_awrNotSavedDescription: "Non hai nessun AWR salvato. Premi per eseguirne la scansione.",
    maternidadConfig_scan: "Scansiona",
    maternidadConfig_continue: "Continua",
    maternidadConfig_alert_error: "Errore",
    maternidadConfig_alert_invalidBackendCrotal: "Il backend non ha restituito un crotale valido da confrontare.",
    maternidadConfig_alert_awrNotConnected: "AWR non connesso",
    maternidadConfig_alert_connectSwordBeforeContinue: "Collega un lettore prima di continuare.",
    maternidadConfig_alert_couldNotStartReading: "Non è stato possibile avviare la lettura con il lettore.",
    maternidadConfig_alert_missingData: "Dato mancante",
    maternidadConfig_alert_writeCrotalToSearch: "Inserisci un crotale da cercare.",
    maternidadConfig_alert_writeIdToSearch: "Inserisci un ID da cercare.",
    maternidadConfig_alert_notFound: "Non trovato",
    maternidadConfig_alert_noAnimalWithCrotal: "Non esiste alcun animale con quel crotale.",
    maternidadConfig_alert_noAnimalWithId: "Non esiste alcun animale con quell'ID.",
    maternidadConfig_alert_warning: "Avviso",
    maternidadConfig_alert_searchError: "Errore nella ricerca",
    maternidadConfig_alert_networkError: "Errore di rete",
    maternidadConfig_alert_networkErrorMessage: "Non è stato possibile connettersi al server.",
};