export default {
    username: 'Usuari',
    password: 'Clau',
    login: 'Inicia sessió',
    welcome: 'Benvingut',
    change_language: 'Canvia idioma',
    Tabs: 'Inici',

    Lista_instalaciones: 'Instal·lacions',
    Maintenance: 'Manteniment',
    DetallesInstalacion: 'Detalls instal·lació',
    Grabar: 'Gravar',
    EstadoStore: 'Estat store',
    Nodata: 'No hi ha dades',
    DosimacRegistration: 'Alta Dosimac',
    NewDmMaternity: 'Nou Dosimac maternitat',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Canvi Dosimac maternitat',
    NewDmGestation: 'Nou Dosimac gestació',
    UpdDmGestation: 'Canvi Dosimac gestació',
    StartScan: 'Cercar equips DOSIMAC',
    DosimacList: 'Equips DOSIMAC',
    PressToScan: 'Premi',
    DosimacSetup: 'Configuració',
    TestoPresioneAlta: 'Premi el botó per cercar dispositius',
    Instalación_seleccionada: 'Instal·lació seleccionada',
    NoInstalacionSeleccionada: 'No hi ha instal·lació seleccionada',
    BorrarGranja: 'Esborrar granja',
    Deseaborrarlagranja: 'Vol esborrar la granja?',
    Guardar: 'Guardar',
    Cancelar: 'Cancel·lar',
    Aceptar: 'Acceptar',
    NombreGranja: 'Nom de la granja',
    Localidad: 'Localitat',
    Provincia: 'Província',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Contrasenya Wifi',
    No_hay_dispositivos: 'No hi ha dispositius',
    Aviso: 'Avís',
    SearchingDevices: 'Cercant equips...',
    NoSePuedeBorrarGranja: 'No es pot esborrar una granja nova',
    settings: 'Ajustos',
    softwareVersion: 'Versió de programari',
    numeroCoral: 'Número de corral',
    numeroMaquina: 'Número de màquina',
    Enviar: 'Enviar',
    Salir: 'Sortir',
    Informacion: 'Informació',

    InicioConfiguracion: "Iniciando conexión",
    ConfiguracionWifi: "Configurando...",
    ConfiguracionRealizada: "*Configuración completada*",
    ErrorConfiguracion: "*Error de configuración*",
    CapturaTagCorral: "Capturar tag de corral",
    CorralTag: "Tag de corral",
    versionUint16: "Esta versión del dispositivo solo admite corrales hasta 65000",
    versionUint32: "Esta versión del dispositivo admite corrales hasta 4000000000",
    EnvioConfiguracion: "Envío de configuración",
    NumeroCorral: "Número de corral",
    NumeroMaquina: "Número de máquina",
    Corralnovalido: "Corral no vàlid",
    Númeromáquinanovalido: "Número de màquina no vàlid",
    configuarIntalacion: "Cal configurar almenys una instal·lació",

    gestacionConfig_screenTitle: "Configuració Gestació",
    gestacionConfig_chooseOptionTitle: "Tria una opció",
    gestacionConfig_chooseOptionDescription: "Defineix el flux abans de començar amb el lector.",

    gestacionConfig_entry: "Entrada",
    gestacionConfig_exit: "Sortida",
    gestacionConfig_reading: "Lectura",
    gestacionConfig_search: "Cerca",

    gestacionConfig_entryParamsTitle: "Paràmetres d'entrada",
    gestacionConfig_exitParamsTitle: "Paràmetres de sortida",
    gestacionConfig_entryParamsDescription: "Selecciona el corral i el comportament del flux.",
    gestacionConfig_exitParamsDescription: "Configura el comportament del flux de sortida.",

    gestacionConfig_corralLabel: "Corral",
    gestacionConfig_corralPlaceholder: "Ex: 1",
    gestacionConfig_corralRequired: "Escriu el corral per continuar.",

    gestacionConfig_detectUnknownTitle: "Identificar animals desconeguts",
    gestacionConfig_detectUnknownDescription: "Quan llegeixis un animal sense identificar, podràs assignar-li un ID",

    gestacionConfig_confirmTitle: "Confirmar enviament",
    gestacionConfig_confirmDescription: "Demanarà confirmació abans d'enviar els registres.",

    gestacionConfig_animalSearchTitle: "Cerca d'animal",
    gestacionConfig_animalSearchDescription: "Tria si vols cercar per crotal o per ID.",
    gestacionConfig_searchByCrotal: "Per crotal",
    gestacionConfig_searchById: "Per ID",
    gestacionConfig_manual: "Manual",
    gestacionConfig_withSword: "Amb espasa",

    gestacionConfig_crotalLabelSearch: "Crotal",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Ex: A13",
    gestacionConfig_crotalRequiredSearch: "Escriu un crotal per continuar.",
    gestacionConfig_idRequiredSearch: "Escriu un ID per continuar.",

    gestacionConfig_searchWithSwordHelp: "En continuar, es llegirà l'espasa en aquesta pantalla i es buscarà l'animal amb aquest crotal.",

    gestacionConfig_readingSword: "Llegint espasa...",
    gestacionConfig_waitingMatch: "Esperant coincidència",
    gestacionConfig_searchingAnimal: "Cercant animal...",

    gestacionConfig_readingSwordDescription: "Apropa el crotal al lector per identificar l'animal.",
    gestacionConfig_waitingMatchDescription: "Animal localitzat. Ara apropa a l'espasa el crotal {{crotal}} per confirmar la coincidència.",
    gestacionConfig_searchingAnimalDescription: "Consultant informació de l'animal al backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR no connectat",
    gestacionConfig_awrSavedDescription: "Tens espases desades. Prem per seleccionar-ne una.",
    gestacionConfig_awrNotSavedDescription: "No tens cap espasa desada. Prem per escanejar-ne una.",

    gestacionConfig_scan: "Escanejar",
    gestacionConfig_continue: "Continuar",

    gestacionConfig_alerts_error: "Error",
    gestacionConfig_alerts_networkError: "Error de xarxa",
    gestacionConfig_alerts_networkErrorMessage: "No s'ha pogut connectar amb el servidor.",
    gestacionConfig_alerts_backendNoValidCrotal: "El backend no ha retornat un crotal vàlid per comparar.",
    gestacionConfig_alerts_awrNotConnected: "AWR no connectat",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Connecta una espasa abans de continuar.",
    gestacionConfig_alerts_couldNotStartReading: "No s'ha pogut iniciar la lectura amb l'espasa.",

    gestacionConfig_alerts_missingData: "Falta dada",
    gestacionConfig_alerts_writeCrotalToSearch: "Escriu un crotal per cercar.",
    gestacionConfig_alerts_writeIdToSearch: "Escriu un ID per cercar.",

    gestacionConfig_alerts_notFound: "No trobat",
    gestacionConfig_alerts_animalNotFoundByCrotal: "No existeix cap animal amb aquest crotal.",
    gestacionConfig_alerts_animalNotFoundById: "No existeix cap animal amb aquest ID.",

    gestacionConfig_alerts_warning: "Avís",
    gestacionConfig_alerts_searchError: "Error en la cerca",

    maternidadConfig_screenTitle: "Configuració Maternitat",
    maternidadConfig_chooseOptionTitle: "Tria una opció",
    maternidadConfig_chooseOptionDescription: "Defineix el flux abans de començar amb el lector.",
    maternidadConfig_entry: "Entrada",
    maternidadConfig_exit: "Sortida",
    maternidadConfig_reading: "Lectura",
    maternidadConfig_search: "Cerca",
    maternidadConfig_entryParamsTitle: "Paràmetres d'entrada",
    maternidadConfig_exitParamsTitle: "Paràmetres de sortida",
    maternidadConfig_entryParamsDescription: "Selecciona el corral i el comportament del flux.",
    maternidadConfig_exitParamsDescription: "Configura el comportament del flux de sortida.",
    maternidadConfig_corralLabel: "Corral",
    maternidadConfig_corralPlaceholder: "Ex: 1",
    maternidadConfig_corralRequired: "Escriu el corral per continuar.",
    maternidadConfig_detectUnknownTitle: "Identificar animals desconeguts",
    maternidadConfig_detectUnknownDescription: "Quan llegeixis un animal sense identificar, podràs assignar-li un ID",
    maternidadConfig_confirmTitle: "Confirmar enviament",
    maternidadConfig_confirmDescription: "Demanarà confirmació abans d'enviar cada registre.",
    maternidadConfig_animalSearchTitle: "Cerca d'animal",
    maternidadConfig_animalSearchDescription: "Tria si vols cercar per crotal o per ID.",
    maternidadConfig_searchByCrotal: "Per crotal",
    maternidadConfig_searchById: "Per ID",
    maternidadConfig_manual: "Manual",
    maternidadConfig_withSword: "Amb espasa",
    maternidadConfig_crotalLabelSearch: "Crotal",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Ex: A13",
    maternidadConfig_crotalRequiredSearch: "Escriu un crotal per continuar.",
    maternidadConfig_idRequiredSearch: "Escriu un ID per continuar.",
    maternidadConfig_searchWithSwordHelp: "En prémer Escanejar, es llegirà l'espasa en aquesta pantalla i es buscarà l'animal amb aquest crotal.",
    maternidadConfig_readingSword: "Llegint espasa...",
    maternidadConfig_waitingMatch: "Esperant coincidència",
    maternidadConfig_searchingAnimal: "Cercant animal...",
    maternidadConfig_readingSwordDescription: "Apropa el crotal al lector per identificar l'animal.",
    maternidadConfig_waitingMatchDescription: "Animal localitzat. Ara apropa a l'espasa el crotal {{crotal}} per confirmar la coincidència.",
    maternidadConfig_searchingAnimalDescription: "Consultant informació de l'animal al backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR no connectat",
    maternidadConfig_awrSavedDescription: "Tens AWR desades. Prem per seleccionar-ne una.",
    maternidadConfig_awrNotSavedDescription: "No tens cap AWR desada. Prem per escanejar-ne una.",
    maternidadConfig_scan: "Escanejar",
    maternidadConfig_continue: "Continuar",
    maternidadConfig_alert_error: "Error",
    maternidadConfig_alert_invalidBackendCrotal: "El backend no ha retornat un crotal vàlid per comparar.",
    maternidadConfig_alert_awrNotConnected: "AWR no connectat",
    maternidadConfig_alert_connectSwordBeforeContinue: "Connecta una espasa abans de continuar.",
    maternidadConfig_alert_couldNotStartReading: "No s'ha pogut iniciar la lectura amb l'espasa.",
    maternidadConfig_alert_missingData: "Falten dades",
    maternidadConfig_alert_writeCrotalToSearch: "Escriu un crotal per cercar.",
    maternidadConfig_alert_writeIdToSearch: "Escriu un ID per cercar.",
    maternidadConfig_alert_notFound: "No trobat",
    maternidadConfig_alert_noAnimalWithCrotal: "No existeix cap animal amb aquest crotal.",
    maternidadConfig_alert_noAnimalWithId: "No existeix cap animal amb aquest ID.",
    maternidadConfig_alert_warning: "Avís",
    maternidadConfig_alert_searchError: "Error en la cerca",
    maternidadConfig_alert_networkError: "Error de xarxa",
    maternidadConfig_alert_networkErrorMessage: "No s'ha pogut connectar amb el servidor.",
};