import { Server } from "http";
import { config } from "process";

/* eslint-disable prettier/prettier */
export default {
   username: 'Username',
   password: 'Clave',
   Server: 'Server IP',
   login: 'Login',
   welcome: 'Bienvenido',
   change_language: 'Cambia idioma',
   Tabs: 'Inicio',


   Lista_instalaciones: 'Instalaciones',
   Maintenance: 'Mantenimiento',
   DetallesInstalacion: 'Detalles Instación',
   Grabar: 'Grabar',
   EstadoStore: 'Estado store',
   Nodata: 'No hay datos',
   DosimacRegistration: 'Alta Dosimac',
   NewDmMaternity: 'Nuevo Dosimac maternidad',
   DosimacG: 'Dosimac-G',
   DosimacI: 'Dosimac-I',
   UpdDmMaternity: 'Cambio Dosimac maternidad',
   NewDmGestation: 'Nuevo Dosimac gestación',
   UpdDmGestation: 'Cambio dosimac gestación',
   StartScan: 'Buscar equipos DOSIMAC',
   DosimacList: 'Equipos DOSIMAC',
   PressToScan: 'Pulse',
   DosimacSetup: 'Configuracion',
   TestoPresioneAlta: "Presione sobre el boton para buscar dispositivos DOSIMAC",
   Instalación_seleccionada: "Instalación seleccionada",
   NoInstalacionSeleccionada: "No hay instalación seleccionada",
   BorrarGranja: "Borrar granja",
   Deseaborrarlagranja: "¿Desea borrar la granja?",
   Guardar: 'Guardar',
   Cancelar: 'Cancelar',
   Aceptar: 'Aceptar',
   NombreGranja: 'Farm name',
   Localidad: 'Location',
   Provincia: 'Province',
   NombreWifi: 'Wifi SSID',
   PasswordWifi: 'Wifi password',

   No_hay_dispositivos: 'No hay dispositivos',
   Aviso: 'Aviso',
   SearchingDevices: 'Buscando equipos...',
   NoSePuedeBorrarGranja: "No se puede borrar una granja nueva",
   settings: 'Ajustes',
   softwareVersion: "software Version",
   configuarIntalacion: "Debe configurar al menos una instalación",
   numeroCoral: "Número de corral",
   numeroMaquina: "Número de máquina",
   Enviar: "Enviar",
   Salir: "Salir",
   Informacion: "Información",

   InicioConfiguracion: "Iniciando conexión",
   ConfiguracionWifi: "Configurando...",
   ConfiguracionRealizada: "*Configuración realizada*",
   ErrorConfiguracion: "*Error de configuración*",
   CapturaTagCorral: "Capturar tag de corral",
   CorralTag: "corral tag",
   versionUint16: "Esta versión del dispositivo solo admite corrales hasta 65000",
   versionUint32: "Esta versión del dispositivo admite corrales hasta 4000000000",
   EnvioConfiguracion: "Envío de configuración",
   NumeroCorral: "Número de corral",
   NumeroMaquina: "Número de máquina",
   Corralnovalido: "Corral no válido",
   Numeromaquinanovalido: "Número de máquina no válido",

   gestacionConfig_screenTitle: "Configuración Gestación",
   gestacionConfig_chooseOptionTitle: "Elige una opción",
   gestacionConfig_chooseOptionDescription: "Define el flujo antes de empezar con el lector.",

   gestacionConfig_entry: "Entrada",
   gestacionConfig_exit: "Salida",
   gestacionConfig_reading: "Lectura",
   gestacionConfig_search: "Búsqueda",

   gestacionConfig_entryParamsTitle: "Parámetros de entrada",
   gestacionConfig_exitParamsTitle: "Parámetros de salida",
   gestacionConfig_entryParamsDescription: "Selecciona el corral y el comportamiento del flujo.",
   gestacionConfig_exitParamsDescription: "Configura el comportamiento del flujo de salida.",

   gestacionConfig_corralLabel: "Corral",
   gestacionConfig_corralPlaceholder: "Ej: 1",
   gestacionConfig_corralRequired: "Escribe el corral para continuar.",

   gestacionConfig_detectUnknownTitle: "Identificar animales desconocidos",
   gestacionConfig_detectUnknownDescription: "Cuando leas un animal sin identificar, podrás asignarle un ID",

   gestacionConfig_confirmTitle: "Confirmar envío",
   gestacionConfig_confirmDescription: "Pedirá confirmación antes de enviar los registros.",

   gestacionConfig_animalSearchTitle: "Búsqueda de animal",
   gestacionConfig_animalSearchDescription: "Elige si quieres buscar por crotal o por ID.",
   gestacionConfig_searchByCrotal: "Por crotal",
   gestacionConfig_searchById: "Por ID",
   gestacionConfig_manual: "Manual",
   gestacionConfig_withSword: "Con espada",

   gestacionConfig_crotalLabelSearch: "Crotal",
   gestacionConfig_idLabelSearch: "ID",
   gestacionConfig_crotalPlaceholderSearch: "Ej: 982091072397436",
   gestacionConfig_idPlaceholderSearch: "Ej: A13",
   gestacionConfig_crotalRequiredSearch: "Escribe un crotal para continuar.",
   gestacionConfig_idRequiredSearch: "Escribe un ID para continuar.",

   gestacionConfig_searchWithSwordHelp: "Al continuar, se leerá la espada en esta pantalla y se buscará el animal con ese crotal.",

   gestacionConfig_readingSword: "Leyendo espada...",
   gestacionConfig_waitingMatch: "Esperando coincidencia",
   gestacionConfig_searchingAnimal: "Buscando animal...",

   gestacionConfig_readingSwordDescription: "Acerca el crotal al lector para identificar el animal.",
   gestacionConfig_waitingMatchDescription: "Animal localizado. Ahora acerca a la espada el crotal {{crotal}} para confirmar la coincidencia.",
   gestacionConfig_searchingAnimalDescription: "Consultando información del animal en el backend.",

   gestacionConfig_awrDisconnectedTitle: "AWR no conectado",
   gestacionConfig_awrSavedDescription: "Tienes espadas guardadas. Pulsa para seleccionar una.",
   gestacionConfig_awrNotSavedDescription: "No tienes ninguna espada guardada. Pulsa para escanear una.",

   gestacionConfig_scan: "Escanear",
   gestacionConfig_continue: "Continuar",

   gestacionConfig_alerts_error: "Error",
   gestacionConfig_alerts_networkError: "Error de red",
   gestacionConfig_alerts_networkErrorMessage: "No se pudo conectar con el servidor.",
   gestacionConfig_alerts_backendNoValidCrotal: "El backend no devolvió un crotal válido para comparar.",
   gestacionConfig_alerts_awrNotConnected: "AWR no conectado",
   gestacionConfig_alerts_connectSwordBeforeContinue: "Conecta una espada antes de continuar.",
   gestacionConfig_alerts_couldNotStartReading: "No se pudo iniciar la lectura con la espada.",

   gestacionConfig_alerts_missingData: "Falta dato",
   gestacionConfig_alerts_writeCrotalToSearch: "Escribe un crotal para buscar.",
   gestacionConfig_alerts_writeIdToSearch: "Escribe un ID para buscar.",

   gestacionConfig_alerts_notFound: "No encontrado",
   gestacionConfig_alerts_animalNotFoundByCrotal: "No existe ningún animal con ese crotal.",
   gestacionConfig_alerts_animalNotFoundById: "No existe ningún animal con ese ID.",

   gestacionConfig_alerts_warning: "Aviso",
   gestacionConfig_alerts_searchError: "Error en la búsqueda",


   maternidadConfig_screenTitle: "Configuración Maternidad",
   maternidadConfig_chooseOptionTitle: "Elige una opción",
   maternidadConfig_chooseOptionDescription: "Define el flujo antes de empezar con el lector.",
   maternidadConfig_entry: "Entrada",
   maternidadConfig_exit: "Salida",
   maternidadConfig_reading: "Lectura",
   maternidadConfig_search: "Búsqueda",
   maternidadConfig_entryParamsTitle: "Parámetros de entrada",
   maternidadConfig_exitParamsTitle: "Parámetros de salida",
   maternidadConfig_entryParamsDescription: "Selecciona el corral y el comportamiento del flujo.",
   maternidadConfig_exitParamsDescription: "Configura el comportamiento del flujo de salida.",
   maternidadConfig_corralLabel: "Corral",
   maternidadConfig_corralPlaceholder: "Ej: 1",
   maternidadConfig_corralRequired: "Escribe el corral para continuar.",
   maternidadConfig_detectUnknownTitle: "Identificar animales desconocidos",
   maternidadConfig_detectUnknownDescription: "Cuando leas un animal sin identificar, podrás asignarle un ID",
   maternidadConfig_confirmTitle: "Confirmar envío",
   maternidadConfig_confirmDescription: "Pedirá confirmación antes de enviar cada registro.",
   maternidadConfig_animalSearchTitle: "Búsqueda de animal",
   maternidadConfig_animalSearchDescription: "Elige si quieres buscar por crotal o por ID.",
   maternidadConfig_searchByCrotal: "Por crotal",
   maternidadConfig_searchById: "Por ID",
   maternidadConfig_manual: "Manual",
   maternidadConfig_withSword: "Con espada",
   maternidadConfig_crotalLabelSearch: "Crotal",
   maternidadConfig_idLabelSearch: "ID",
   maternidadConfig_crotalPlaceholderSearch: "Ej: 982091072397436",
   maternidadConfig_idPlaceholderSearch: "Ej: A13",
   maternidadConfig_crotalRequiredSearch: "Escribe un crotal para continuar.",
   maternidadConfig_idRequiredSearch: "Escribe un ID para continuar.",
   maternidadConfig_searchWithSwordHelp: "Al pulsar Escanear, se leerá la espada en esta pantalla y se buscará el animal con ese crotal.",
   maternidadConfig_readingSword: "Leyendo espada...",
   maternidadConfig_waitingMatch: "Esperando coincidencia",
   maternidadConfig_searchingAnimal: "Buscando animal...",
   maternidadConfig_readingSwordDescription: "Acerca el crotal al lector para identificar el animal.",
   maternidadConfig_waitingMatchDescription: "Animal localizado. Ahora acerca a la espada el crotal {{crotal}} para confirmar la coincidencia.",
   maternidadConfig_searchingAnimalDescription: "Consultando información del animal en el backend.",
   maternidadConfig_awrDisconnectedTitle: "AWR no conectado",
   maternidadConfig_awrSavedDescription: "Tienes AWR guardadas. Pulsa para seleccionar una.",
   maternidadConfig_awrNotSavedDescription: "No tienes ninguna AWR guardada. Pulsa para escanear una.",
   maternidadConfig_scan: "Escanear",
   maternidadConfig_continue: "Continuar",
   maternidadConfig_alert_error: "Error",
   maternidadConfig_alert_invalidBackendCrotal: "El backend no devolvió un crotal válido para comparar.",
   maternidadConfig_alert_awrNotConnected: "AWR no conectado",
   maternidadConfig_alert_connectSwordBeforeContinue: "Conecta una espada antes de continuar.",
   maternidadConfig_alert_couldNotStartReading: "No se pudo iniciar la lectura con la espada.",
   maternidadConfig_alert_missingData: "Falta dato",
   maternidadConfig_alert_writeCrotalToSearch: "Escribe un crotal para buscar.",
   maternidadConfig_alert_writeIdToSearch: "Escribe un ID para buscar.",
   maternidadConfig_alert_notFound: "No encontrado",
   maternidadConfig_alert_noAnimalWithCrotal: "No existe ningún animal con ese crotal.",
   maternidadConfig_alert_noAnimalWithId: "No existe ningún animal con ese ID.",
   maternidadConfig_alert_warning: "Aviso",
   maternidadConfig_alert_searchError: "Error en la búsqueda",
   maternidadConfig_alert_networkError: "Error de red",
   maternidadConfig_alert_networkErrorMessage: "No se pudo conectar con el servidor.",

};