import { config } from "process";

export default {
    username: 'Пользователь',
    password: 'Пароль',
    login: 'Войти',
    welcome: 'Добро пожаловать',
    change_language: 'Сменить язык',
    Tabs: 'Главная',

    Lista_instalaciones: 'Установки',
    Maintenance: 'Техническое обслуживание',
    DetallesInstalacion: 'Детали установки',
    Grabar: 'Сохранить',
    EstadoStore: 'Статус store',
    Nodata: 'Нет данных',
    DosimacRegistration: 'Регистрация',
    NewDmMaternity: 'Новый Dosimac родильное',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Изменение Dosimac родильное',
    NewDmGestation: 'Новый Dosimac беременность',
    UpdDmGestation: 'Изменение Dosimac беременность',
    StartScan: 'Поиск устройств DOSIMAC',
    DosimacList: 'Устройства DOSIMAC',
    PressToScan: 'Нажмите',
    DosimacSetup: 'Конфигурация',
    TestoPresioneAlta: 'Нажмите кнопку, чтобы найти устройства',
    Instalación_seleccionada: 'Выбранная установка',
    NoInstalacionSeleccionada: 'Нет выбранной установки',
    BorrarGranja: 'Удалить ферму',
    Deseaborrarlagranja: 'Хотите удалить ферму?',
    Guardar: 'Сохранить',
    Cancelar: 'Отмена',
    Aceptar: 'Принять',
    NombreGranja: 'Название фермы',
    Localidad: 'Местоположение',
    Provincia: 'Область',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Пароль Wifi',
    No_hay_dispositivos: 'Нет устройств',
    Aviso: 'Уведомление',
    SearchingDevices: 'Поиск устройств...',
    NoSePuedeBorrarGranja: 'Нельзя удалить новую ферму',
    settings: 'Настройки',
    softwareVersion: 'Версия ПО',
    numeroCoral: 'Номер загона',
    numeroMaquina: 'Номер машины',
    Enviar: 'Отправить',
    Salir: 'Выйти',
    Informacion: 'Информация',

    InicioConfiguracion: "Запуск подключения",
    ConfiguracionWifi: "Настройка...",
    ConfiguracionRealizada: "*Настройка завершена*",
    ErrorConfiguracion: "*Ошибка настройки*",
    CapturaTagCorral: "Считать тег загона",
    CorralTag: "Тег загона",
    versionUint16: "Эта версия устройства поддерживает номера загонов только до 65000",
    versionUint32: "Эта версия устройства поддерживает номера загонов до 4000000000",
    EnvioConfiguracion: "Отправка конфигурации",
    NumeroCorral: "Номер загона",
    NumeroMaquina: "Номер машины",
    Corralnovalido: "Недопустимый загон",
    Númeromáquinanovalido: "Недопустимый номер машины",
    configuarIntalacion: "Настройте установку, чтобы продолжить",

    gestacionConfig_screenTitle: "Настройки гестации",
    gestacionConfig_chooseOptionTitle: "Выберите вариант",
    gestacionConfig_chooseOptionDescription: "Определите поток перед началом работы со считывателем.",

    gestacionConfig_entry: "Вход",
    gestacionConfig_exit: "Выход",
    gestacionConfig_reading: "Считывание",
    gestacionConfig_search: "Поиск",

    gestacionConfig_entryParamsTitle: "Параметры входа",
    gestacionConfig_exitParamsTitle: "Параметры выхода",
    gestacionConfig_entryParamsDescription: "Выберите загон и поведение потока.",
    gestacionConfig_exitParamsDescription: "Настройте поведение потока выхода.",

    gestacionConfig_corralLabel: "Загон",
    gestacionConfig_corralPlaceholder: "Напр.: 1",
    gestacionConfig_corralRequired: "Введите загон, чтобы продолжить.",

    gestacionConfig_detectUnknownTitle: "Определять неизвестных животных",
    gestacionConfig_detectUnknownDescription: "Когда вы считаете неидентифицированное животное, вы сможете назначить ему ID",

    gestacionConfig_confirmTitle: "Подтвердить отправку",
    gestacionConfig_confirmDescription: "Перед отправкой записей будет запрошено подтверждение.",

    gestacionConfig_animalSearchTitle: "Поиск животного",
    gestacionConfig_animalSearchDescription: "Выберите поиск по бирке или по ID.",
    gestacionConfig_searchByCrotal: "По бирке",
    gestacionConfig_searchById: "По ID",
    gestacionConfig_manual: "Вручную",
    gestacionConfig_withSword: "Со сканером",

    gestacionConfig_crotalLabelSearch: "Бирка",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Напр.: 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Напр.: A13",
    gestacionConfig_crotalRequiredSearch: "Введите бирку, чтобы продолжить.",
    gestacionConfig_idRequiredSearch: "Введите ID, чтобы продолжить.",

    gestacionConfig_searchWithSwordHelp: "После продолжения на этом экране будет выполнено считывание сканером, и животное будет найдено по этой бирке.",

    gestacionConfig_readingSword: "Считывание сканером...",
    gestacionConfig_waitingMatch: "Ожидание совпадения",
    gestacionConfig_searchingAnimal: "Поиск животного...",

    gestacionConfig_readingSwordDescription: "Поднесите бирку к считывателю, чтобы идентифицировать животное.",
    gestacionConfig_waitingMatchDescription: "Животное найдено. Теперь поднесите к сканеру бирку {{crotal}}, чтобы подтвердить совпадение.",
    gestacionConfig_searchingAnimalDescription: "Проверка информации о животном в backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR не подключён",
    gestacionConfig_awrSavedDescription: "У вас есть сохранённые сканеры. Нажмите, чтобы выбрать один.",
    gestacionConfig_awrNotSavedDescription: "У вас нет сохранённых сканеров. Нажмите, чтобы отсканировать один.",

    gestacionConfig_scan: "Сканировать",
    gestacionConfig_continue: "Продолжить",

    gestacionConfig_alerts_error: "Ошибка",
    gestacionConfig_alerts_networkError: "Ошибка сети",
    gestacionConfig_alerts_networkErrorMessage: "Не удалось подключиться к серверу.",
    gestacionConfig_alerts_backendNoValidCrotal: "Backend не вернул корректную бирку для сравнения.",
    gestacionConfig_alerts_awrNotConnected: "AWR не подключён",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Подключите сканер перед продолжением.",
    gestacionConfig_alerts_couldNotStartReading: "Не удалось начать считывание сканером.",

    gestacionConfig_alerts_missingData: "Недостаточно данных",
    gestacionConfig_alerts_writeCrotalToSearch: "Введите бирку для поиска.",
    gestacionConfig_alerts_writeIdToSearch: "Введите ID для поиска.",

    gestacionConfig_alerts_notFound: "Не найдено",
    gestacionConfig_alerts_animalNotFoundByCrotal: "Животное с такой биркой не существует.",
    gestacionConfig_alerts_animalNotFoundById: "Животное с таким ID не существует.",

    gestacionConfig_alerts_warning: "Предупреждение",
    gestacionConfig_alerts_searchError: "Ошибка поиска",

    maternidadConfig_screenTitle: "Настройки материнского отделения",
    maternidadConfig_chooseOptionTitle: "Выберите вариант",
    maternidadConfig_chooseOptionDescription: "Определите поток перед началом работы со считывателем.",
    maternidadConfig_entry: "Вход",
    maternidadConfig_exit: "Выход",
    maternidadConfig_reading: "Считывание",
    maternidadConfig_search: "Поиск",
    maternidadConfig_entryParamsTitle: "Параметры входа",
    maternidadConfig_exitParamsTitle: "Параметры выхода",
    maternidadConfig_entryParamsDescription: "Выберите загон и поведение потока.",
    maternidadConfig_exitParamsDescription: "Настройте поведение потока выхода.",
    maternidadConfig_corralLabel: "Загон",
    maternidadConfig_corralPlaceholder: "Напр.: 1",
    maternidadConfig_corralRequired: "Введите загон, чтобы продолжить.",
    maternidadConfig_detectUnknownTitle: "Определять неизвестных животных",
    maternidadConfig_detectUnknownDescription: "При считывании неидентифицированного животного вы сможете назначить ему ID",
    maternidadConfig_confirmTitle: "Подтверждать отправку",
    maternidadConfig_confirmDescription: "Перед отправкой каждой записи будет запрашиваться подтверждение.",
    maternidadConfig_animalSearchTitle: "Поиск животного",
    maternidadConfig_animalSearchDescription: "Выберите поиск по crotal или по ID.",
    maternidadConfig_searchByCrotal: "По crotal",
    maternidadConfig_searchById: "По ID",
    maternidadConfig_manual: "Вручную",
    maternidadConfig_withSword: "Со сканером",
    maternidadConfig_crotalLabelSearch: "Crotal",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Напр.: 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Напр.: A13",
    maternidadConfig_crotalRequiredSearch: "Введите crotal, чтобы продолжить.",
    maternidadConfig_idRequiredSearch: "Введите ID, чтобы продолжить.",
    maternidadConfig_searchWithSwordHelp: "При нажатии Сканировать сканер будет использоваться на этом экране, и животное будет найдено по этому crotal.",
    maternidadConfig_readingSword: "Считывание сканера...",
    maternidadConfig_waitingMatch: "Ожидание совпадения",
    maternidadConfig_searchingAnimal: "Поиск животного...",
    maternidadConfig_readingSwordDescription: "Поднесите crotal к считывателю, чтобы определить животное.",
    maternidadConfig_waitingMatchDescription: "Животное найдено. Теперь поднесите crotal {{crotal}} к сканеру, чтобы подтвердить совпадение.",
    maternidadConfig_searchingAnimalDescription: "Получение информации о животном из backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR не подключен",
    maternidadConfig_awrSavedDescription: "У вас есть сохранённые AWR. Нажмите, чтобы выбрать одну.",
    maternidadConfig_awrNotSavedDescription: "У вас нет сохранённых AWR. Нажмите, чтобы просканировать одну.",
    maternidadConfig_scan: "Сканировать",
    maternidadConfig_continue: "Продолжить",
    maternidadConfig_alert_error: "Ошибка",
    maternidadConfig_alert_invalidBackendCrotal: "Backend не вернул корректный crotal для сравнения.",
    maternidadConfig_alert_awrNotConnected: "AWR не подключен",
    maternidadConfig_alert_connectSwordBeforeContinue: "Подключите сканер перед продолжением.",
    maternidadConfig_alert_couldNotStartReading: "Не удалось начать считывание со сканером.",
    maternidadConfig_alert_missingData: "Не хватает данных",
    maternidadConfig_alert_writeCrotalToSearch: "Введите crotal для поиска.",
    maternidadConfig_alert_writeIdToSearch: "Введите ID для поиска.",
    maternidadConfig_alert_notFound: "Не найдено",
    maternidadConfig_alert_noAnimalWithCrotal: "Животное с таким crotal не найдено.",
    maternidadConfig_alert_noAnimalWithId: "Животное с таким ID не найдено.",
    maternidadConfig_alert_warning: "Предупреждение",
    maternidadConfig_alert_searchError: "Ошибка поиска",
    maternidadConfig_alert_networkError: "Ошибка сети",
    maternidadConfig_alert_networkErrorMessage: "Не удалось подключиться к серверу.",

};