export default {
    username: 'Utilizador',
    password: 'Palavra-passe',
    login: 'Iniciar sessão',
    welcome: 'Bem-vindo',
    change_language: 'Mudar idioma',
    Tabs: 'Início',

    Lista_instalaciones: 'Instalações',
    Maintenance: 'Manutenção',
    DetallesInstalacion: 'Detalhes da instalação',
    Grabar: 'Gravar',
    EstadoStore: 'Estado da store',
    Nodata: 'Sem dados',
    DosimacRegistration: 'Registo',
    NewDmMaternity: 'Novo Dosimac maternidade',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Atualizar Dosimac maternidade',
    NewDmGestation: 'Novo Dosimac gestação',
    UpdDmGestation: 'Atualizar Dosimac gestação',
    StartScan: 'Procurar equipamentos DOSIMAC',
    DosimacList: 'Equipamentos DOSIMAC',
    PressToScan: 'Prima',
    DosimacSetup: 'Configuração',
    TestoPresioneAlta: 'Prima o botão para procurar dispositivos',
    Instalación_seleccionada: 'Instalação selecionada',
    NoInstalacionSeleccionada: 'Nenhuma instalação selecionada',
    BorrarGranja: 'Eliminar quinta',
    Deseaborrarlagranja: 'Deseja eliminar a quinta?',
    Guardar: 'Guardar',
    Cancelar: 'Cancelar',
    Aceptar: 'Aceitar',
    NombreGranja: 'Nome da quinta',
    Localidad: 'Localidade',
    Provincia: 'Província',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Palavra-passe do Wifi',
    No_hay_dispositivos: 'Sem dispositivos',
    Aviso: 'Aviso',
    SearchingDevices: 'A procurar dispositivos...',
    NoSePuedeBorrarGranja: 'Não é possível eliminar uma quinta nova',
    settings: 'Definições',
    softwareVersion: 'Versão do software',
    numeroCoral: 'Número do curral',
    numeroMaquina: 'Número da máquina',
    Enviar: 'Enviar',
    Salir: 'Sair',
    Informacion: 'Informação',

    InicioConfiguracion: "A iniciar ligação",
    ConfiguracionWifi: "A configurar...",
    ConfiguracionRealizada: "*Configuração concluída*",
    ErrorConfiguracion: "*Erro de configuração*",
    CapturaTagCorral: "Capturar tag do curral",
    CorralTag: "Tag do curral",
    versionUint16: "Esta versão do dispositivo só suporta currais até 65000",
    versionUint32: "Esta versão do dispositivo suporta currais até 4000000000",
    EnvioConfiguracion: "A enviar configuração",
    NumeroCorral: "Número do curral",
    NumeroMaquina: "Número da máquina",
    Corralnovalido: "Curral não válido",
    Númeromáquinanovalido: "Número da máquina não válido",
    configuarIntalacion: "Deve configurar pelo menos uma instalação",
    gestacionConfig_screenTitle: "Configuração Gestação",
    gestacionConfig_chooseOptionTitle: "Escolhe uma opção",
    gestacionConfig_chooseOptionDescription: "Define o fluxo antes de começar com o leitor.",

    gestacionConfig_entry: "Entrada",
    gestacionConfig_exit: "Saída",
    gestacionConfig_reading: "Leitura",
    gestacionConfig_search: "Pesquisa",

    gestacionConfig_entryParamsTitle: "Parâmetros de entrada",
    gestacionConfig_exitParamsTitle: "Parâmetros de saída",
    gestacionConfig_entryParamsDescription: "Seleciona o curral e o comportamento do fluxo.",
    gestacionConfig_exitParamsDescription: "Configura o comportamento do fluxo de saída.",

    gestacionConfig_corralLabel: "Curral",
    gestacionConfig_corralPlaceholder: "Ex: 1",
    gestacionConfig_corralRequired: "Escreve o curral para continuar.",

    gestacionConfig_detectUnknownTitle: "Identificar animais desconhecidos",
    gestacionConfig_detectUnknownDescription: "Quando leres um animal sem identificação, poderás atribuir-lhe um ID",

    gestacionConfig_confirmTitle: "Confirmar envio",
    gestacionConfig_confirmDescription: "Vai pedir confirmação antes de enviar os registos.",

    gestacionConfig_animalSearchTitle: "Pesquisa de animal",
    gestacionConfig_animalSearchDescription: "Escolhe se queres pesquisar por crotal ou por ID.",
    gestacionConfig_searchByCrotal: "Por crotal",
    gestacionConfig_searchById: "Por ID",
    gestacionConfig_manual: "Manual",
    gestacionConfig_withSword: "Com espada",

    gestacionConfig_crotalLabelSearch: "Crotal",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Ex: A13",
    gestacionConfig_crotalRequiredSearch: "Escreve um crotal para continuar.",
    gestacionConfig_idRequiredSearch: "Escreve um ID para continuar.",

    gestacionConfig_searchWithSwordHelp: "Ao continuar, a espada será lida neste ecrã e o animal será pesquisado com esse crotal.",

    gestacionConfig_readingSword: "A ler espada...",
    gestacionConfig_waitingMatch: "À espera de correspondência",
    gestacionConfig_searchingAnimal: "A pesquisar animal...",

    gestacionConfig_readingSwordDescription: "Aproxima o crotal do leitor para identificar o animal.",
    gestacionConfig_waitingMatchDescription: "Animal localizado. Agora aproxima à espada o crotal {{crotal}} para confirmar a correspondência.",
    gestacionConfig_searchingAnimalDescription: "A consultar informação do animal no backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR não ligado",
    gestacionConfig_awrSavedDescription: "Tens espadas guardadas. Prime para selecionar uma.",
    gestacionConfig_awrNotSavedDescription: "Não tens nenhuma espada guardada. Prime para digitalizar uma.",

    gestacionConfig_scan: "Digitalizar",
    gestacionConfig_continue: "Continuar",

    gestacionConfig_alerts_error: "Erro",
    gestacionConfig_alerts_networkError: "Erro de rede",
    gestacionConfig_alerts_networkErrorMessage: "Não foi possível ligar ao servidor.",
    gestacionConfig_alerts_backendNoValidCrotal: "O backend não devolveu um crotal válido para comparar.",
    gestacionConfig_alerts_awrNotConnected: "AWR não ligado",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Liga uma espada antes de continuar.",
    gestacionConfig_alerts_couldNotStartReading: "Não foi possível iniciar a leitura com a espada.",

    gestacionConfig_alerts_missingData: "Falta dado",
    gestacionConfig_alerts_writeCrotalToSearch: "Escreve um crotal para pesquisar.",
    gestacionConfig_alerts_writeIdToSearch: "Escreve um ID para pesquisar.",

    gestacionConfig_alerts_notFound: "Não encontrado",
    gestacionConfig_alerts_animalNotFoundByCrotal: "Não existe nenhum animal com esse crotal.",
    gestacionConfig_alerts_animalNotFoundById: "Não existe nenhum animal com esse ID.",

    gestacionConfig_alerts_warning: "Aviso",
    gestacionConfig_alerts_searchError: "Erro na pesquisa",

    maternidadConfig_screenTitle: "Configuração Maternidade",
    maternidadConfig_chooseOptionTitle: "Escolhe uma opção",
    maternidadConfig_chooseOptionDescription: "Define o fluxo antes de começar com o leitor.",
    maternidadConfig_entry: "Entrada",
    maternidadConfig_exit: "Saída",
    maternidadConfig_reading: "Leitura",
    maternidadConfig_search: "Pesquisa",
    maternidadConfig_entryParamsTitle: "Parâmetros de entrada",
    maternidadConfig_exitParamsTitle: "Parâmetros de saída",
    maternidadConfig_entryParamsDescription: "Seleciona o curral e o comportamento do fluxo.",
    maternidadConfig_exitParamsDescription: "Configura o comportamento do fluxo de saída.",
    maternidadConfig_corralLabel: "Curral",
    maternidadConfig_corralPlaceholder: "Ex: 1",
    maternidadConfig_corralRequired: "Escreve o curral para continuar.",
    maternidadConfig_detectUnknownTitle: "Identificar animais desconhecidos",
    maternidadConfig_detectUnknownDescription: "Quando leres um animal sem identificação, poderás atribuir-lhe um ID",
    maternidadConfig_confirmTitle: "Confirmar envio",
    maternidadConfig_confirmDescription: "Irá pedir confirmação antes de enviar cada registo.",
    maternidadConfig_animalSearchTitle: "Pesquisa de animal",
    maternidadConfig_animalSearchDescription: "Escolhe se queres pesquisar por crotal ou por ID.",
    maternidadConfig_searchByCrotal: "Por crotal",
    maternidadConfig_searchById: "Por ID",
    maternidadConfig_manual: "Manual",
    maternidadConfig_withSword: "Com espada",
    maternidadConfig_crotalLabelSearch: "Crotal",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Ex: 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Ex: A13",
    maternidadConfig_crotalRequiredSearch: "Escreve um crotal para continuar.",
    maternidadConfig_idRequiredSearch: "Escreve um ID para continuar.",
    maternidadConfig_searchWithSwordHelp: "Ao premir Digitalizar, a espada será lida neste ecrã e o animal será pesquisado com esse crotal.",
    maternidadConfig_readingSword: "A ler espada...",
    maternidadConfig_waitingMatch: "À espera de correspondência",
    maternidadConfig_searchingAnimal: "A pesquisar animal...",
    maternidadConfig_readingSwordDescription: "Aproxima o crotal do leitor para identificar o animal.",
    maternidadConfig_waitingMatchDescription: "Animal localizado. Agora aproxima à espada o crotal {{crotal}} para confirmar a correspondência.",
    maternidadConfig_searchingAnimalDescription: "A consultar informação do animal no backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR não ligado",
    maternidadConfig_awrSavedDescription: "Tens AWR guardadas. Toca para selecionar uma.",
    maternidadConfig_awrNotSavedDescription: "Não tens nenhuma AWR guardada. Toca para digitalizar uma.",
    maternidadConfig_scan: "Digitalizar",
    maternidadConfig_continue: "Continuar",
    maternidadConfig_alert_error: "Erro",
    maternidadConfig_alert_invalidBackendCrotal: "O backend não devolveu um crotal válido para comparar.",
    maternidadConfig_alert_awrNotConnected: "AWR não ligado",
    maternidadConfig_alert_connectSwordBeforeContinue: "Liga uma espada antes de continuar.",
    maternidadConfig_alert_couldNotStartReading: "Não foi possível iniciar a leitura com a espada.",
    maternidadConfig_alert_missingData: "Falta dado",
    maternidadConfig_alert_writeCrotalToSearch: "Escreve um crotal para pesquisar.",
    maternidadConfig_alert_writeIdToSearch: "Escreve um ID para pesquisar.",
    maternidadConfig_alert_notFound: "Não encontrado",
    maternidadConfig_alert_noAnimalWithCrotal: "Não existe nenhum animal com esse crotal.",
    maternidadConfig_alert_noAnimalWithId: "Não existe nenhum animal com esse ID.",
    maternidadConfig_alert_warning: "Aviso",
    maternidadConfig_alert_searchError: "Erro na pesquisa",
    maternidadConfig_alert_networkError: "Erro de rede",
    maternidadConfig_alert_networkErrorMessage: "Não foi possível ligar ao servidor.",

}