export default {
    username: 'Користувач',
    password: 'Пароль',
    login: 'Увійти',
    welcome: 'Ласкаво просимо',
    change_language: 'Змінити мову',
    Tabs: 'Головна',

    Lista_instalaciones: 'Установки',
    Maintenance: 'Технічне обслуговування',
    DetallesInstalacion: 'Деталі установки',
    Grabar: 'Зберегти',
    EstadoStore: 'Стан store',
    Nodata: 'Немає даних',
    DosimacRegistration: 'Реєстрація',
    NewDmMaternity: 'Новий Dosimac (пологи)',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Оновлення Dosimac (пологи)',
    NewDmGestation: 'Новий Dosimac (вагітність)',
    UpdDmGestation: 'Оновлення Dosimac (вагітність)',
    StartScan: 'Пошук пристроїв DOSIMAC',
    DosimacList: 'Пристрої DOSIMAC',
    PressToScan: 'Натисніть',
    DosimacSetup: 'Конфігурація',
    TestoPresioneAlta: 'Натисніть кнопку, щоб шукати пристрої',
    Instalación_seleccionada: 'Вибрана установка',
    NoInstalacionSeleccionada: 'Установка не вибрана',
    BorrarGranja: 'Видалити ферму',
    Deseaborrarlagranja: 'Бажаєте видалити ферму?',
    Guardar: 'Зберегти',
    Cancelar: 'Скасувати',
    Aceptar: 'Прийняти',
    NombreGranja: 'Назва ферми',
    Localidad: 'Місцезнаходження',
    Provincia: 'Область',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Пароль Wifi',
    No_hay_dispositivos: 'Немає пристроїв',
    Aviso: 'Повідомлення',
    SearchingDevices: 'Пошук пристроїв...',
    NoSePuedeBorrarGranja: 'Неможливо видалити нову ферму',
    settings: 'Налаштування',
    softwareVersion: 'Версія програмного забезпечення',
    numeroCoral: 'Номер загону',
    numeroMaquina: 'Номер машини',
    Enviar: 'Надіслати',
    Salir: 'Вийти',
    Informacion: 'Інформація',

    InicioConfiguracion: "Запуск підключення",
    ConfiguracionWifi: "Налаштування...",
    ConfiguracionRealizada: "*Налаштування завершено*",
    ErrorConfiguracion: "*Помилка налаштування*",
    CapturaTagCorral: "Зчитати тег загону",
    CorralTag: "Тег загону",
    versionUint16: "Ця версія пристрою підтримує загони лише до 65000",
    versionUint32: "Ця версія пристрою підтримує загони до 4000000000",
    EnvioConfiguracion: "Надсилання конфігурації",
    NumeroCorral: "Номер загону",
    NumeroMaquina: "Номер машини",
    Corralnovalido: 'Невірний загін',
    Númeromáquinanovalido: 'Невірний номер машини',
    configuarIntalacion: "Налаштуйте установку, щоб продовжити",

    gestacionConfig_screenTitle: "Налаштування гестації",
    gestacionConfig_chooseOptionTitle: "Оберіть варіант",
    gestacionConfig_chooseOptionDescription: "Визначте потік перед початком роботи зі зчитувачем.",

    gestacionConfig_entry: "Вхід",
    gestacionConfig_exit: "Вихід",
    gestacionConfig_reading: "Зчитування",
    gestacionConfig_search: "Пошук",

    gestacionConfig_entryParamsTitle: "Параметри входу",
    gestacionConfig_exitParamsTitle: "Параметри виходу",
    gestacionConfig_entryParamsDescription: "Оберіть загін і поведінку потоку.",
    gestacionConfig_exitParamsDescription: "Налаштуйте поведінку потоку виходу.",

    gestacionConfig_corralLabel: "Загін",
    gestacionConfig_corralPlaceholder: "Напр.: 1",
    gestacionConfig_corralRequired: "Введіть загін, щоб продовжити.",

    gestacionConfig_detectUnknownTitle: "Визначати невідомих тварин",
    gestacionConfig_detectUnknownDescription: "Коли ви зчитаєте неідентифіковану тварину, ви зможете призначити їй ID",

    gestacionConfig_confirmTitle: "Підтвердити надсилання",
    gestacionConfig_confirmDescription: "Перед надсиланням записів буде запитано підтвердження.",

    gestacionConfig_animalSearchTitle: "Пошук тварини",
    gestacionConfig_animalSearchDescription: "Оберіть пошук за біркою або за ID.",
    gestacionConfig_searchByCrotal: "За біркою",
    gestacionConfig_searchById: "За ID",
    gestacionConfig_manual: "Вручну",
    gestacionConfig_withSword: "Зі сканером",

    gestacionConfig_crotalLabelSearch: "Бірка",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Напр.: 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Напр.: A13",
    gestacionConfig_crotalRequiredSearch: "Введіть бірку, щоб продовжити.",
    gestacionConfig_idRequiredSearch: "Введіть ID, щоб продовжити.",

    gestacionConfig_searchWithSwordHelp: "Після продовження на цьому екрані буде виконано зчитування сканером, і тварину буде знайдено за цією біркою.",

    gestacionConfig_readingSword: "Зчитування сканером...",
    gestacionConfig_waitingMatch: "Очікування збігу",
    gestacionConfig_searchingAnimal: "Пошук тварини...",

    gestacionConfig_readingSwordDescription: "Піднесіть бірку до зчитувача, щоб ідентифікувати тварину.",
    gestacionConfig_waitingMatchDescription: "Тварину знайдено. Тепер піднесіть до сканера бірку {{crotal}}, щоб підтвердити збіг.",
    gestacionConfig_searchingAnimalDescription: "Перевірка інформації про тварину в backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR не підключено",
    gestacionConfig_awrSavedDescription: "У вас є збережені сканери. Натисніть, щоб вибрати один.",
    gestacionConfig_awrNotSavedDescription: "У вас немає збережених сканерів. Натисніть, щоб відсканувати один.",

    gestacionConfig_scan: "Сканувати",
    gestacionConfig_continue: "Продовжити",

    gestacionConfig_alerts_error: "Помилка",
    gestacionConfig_alerts_networkError: "Помилка мережі",
    gestacionConfig_alerts_networkErrorMessage: "Не вдалося підключитися до сервера.",
    gestacionConfig_alerts_backendNoValidCrotal: "Backend не повернув дійсну бірку для порівняння.",
    gestacionConfig_alerts_awrNotConnected: "AWR не підключено",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Підключіть сканер перед продовженням.",
    gestacionConfig_alerts_couldNotStartReading: "Не вдалося почати зчитування сканером.",

    gestacionConfig_alerts_missingData: "Бракує даних",
    gestacionConfig_alerts_writeCrotalToSearch: "Введіть бірку для пошуку.",
    gestacionConfig_alerts_writeIdToSearch: "Введіть ID для пошуку.",

    gestacionConfig_alerts_notFound: "Не знайдено",
    gestacionConfig_alerts_animalNotFoundByCrotal: "Тварини з такою біркою не існує.",
    gestacionConfig_alerts_animalNotFoundById: "Тварини з таким ID не існує.",

    gestacionConfig_alerts_warning: "Попередження",
    gestacionConfig_alerts_searchError: "Помилка пошуку",

    maternidadConfig_screenTitle: "Налаштування материнського відділення",
    maternidadConfig_chooseOptionTitle: "Оберіть варіант",
    maternidadConfig_chooseOptionDescription: "Визначте потік перед початком роботи зі зчитувачем.",
    maternidadConfig_entry: "Вхід",
    maternidadConfig_exit: "Вихід",
    maternidadConfig_reading: "Зчитування",
    maternidadConfig_search: "Пошук",
    maternidadConfig_entryParamsTitle: "Параметри входу",
    maternidadConfig_exitParamsTitle: "Параметри виходу",
    maternidadConfig_entryParamsDescription: "Виберіть загін і поведінку потоку.",
    maternidadConfig_exitParamsDescription: "Налаштуйте поведінку потоку виходу.",
    maternidadConfig_corralLabel: "Загін",
    maternidadConfig_corralPlaceholder: "Напр.: 1",
    maternidadConfig_corralRequired: "Введіть загін, щоб продовжити.",
    maternidadConfig_detectUnknownTitle: "Визначати невідомих тварин",
    maternidadConfig_detectUnknownDescription: "Коли ви зчитаєте неідентифіковану тварину, ви зможете призначити їй ID",
    maternidadConfig_confirmTitle: "Підтверджувати надсилання",
    maternidadConfig_confirmDescription: "Перед надсиланням кожного запису буде запитано підтвердження.",
    maternidadConfig_animalSearchTitle: "Пошук тварини",
    maternidadConfig_animalSearchDescription: "Оберіть пошук за crotal або за ID.",
    maternidadConfig_searchByCrotal: "За crotal",
    maternidadConfig_searchById: "За ID",
    maternidadConfig_manual: "Вручну",
    maternidadConfig_withSword: "Зі сканером",
    maternidadConfig_crotalLabelSearch: "Crotal",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Напр.: 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Напр.: A13",
    maternidadConfig_crotalRequiredSearch: "Введіть crotal, щоб продовжити.",
    maternidadConfig_idRequiredSearch: "Введіть ID, щоб продовжити.",
    maternidadConfig_searchWithSwordHelp: "Після натискання Сканувати сканер буде використано на цьому екрані, і тварину буде знайдено за цим crotal.",
    maternidadConfig_readingSword: "Зчитування сканера...",
    maternidadConfig_waitingMatch: "Очікування збігу",
    maternidadConfig_searchingAnimal: "Пошук тварини...",
    maternidadConfig_readingSwordDescription: "Піднесіть crotal до зчитувача, щоб визначити тварину.",
    maternidadConfig_waitingMatchDescription: "Тварину знайдено. Тепер піднесіть crotal {{crotal}} до сканера, щоб підтвердити збіг.",
    maternidadConfig_searchingAnimalDescription: "Отримання інформації про тварину з backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR не підключено",
    maternidadConfig_awrSavedDescription: "У вас є збережені AWR. Натисніть, щоб вибрати одну.",
    maternidadConfig_awrNotSavedDescription: "У вас немає збережених AWR. Натисніть, щоб відсканувати одну.",
    maternidadConfig_scan: "Сканувати",
    maternidadConfig_continue: "Продовжити",
    maternidadConfig_alert_error: "Помилка",
    maternidadConfig_alert_invalidBackendCrotal: "Backend не повернув коректний crotal для порівняння.",
    maternidadConfig_alert_awrNotConnected: "AWR не підключено",
    maternidadConfig_alert_connectSwordBeforeContinue: "Підключіть сканер перед продовженням.",
    maternidadConfig_alert_couldNotStartReading: "Не вдалося розпочати зчитування сканером.",
    maternidadConfig_alert_missingData: "Бракує даних",
    maternidadConfig_alert_writeCrotalToSearch: "Введіть crotal для пошуку.",
    maternidadConfig_alert_writeIdToSearch: "Введіть ID для пошуку.",
    maternidadConfig_alert_notFound: "Не знайдено",
    maternidadConfig_alert_noAnimalWithCrotal: "Тварину з таким crotal не знайдено.",
    maternidadConfig_alert_noAnimalWithId: "Тварину з таким ID не знайдено.",
    maternidadConfig_alert_warning: "Попередження",
    maternidadConfig_alert_searchError: "Помилка пошуку",
    maternidadConfig_alert_networkError: "Помилка мережі",
    maternidadConfig_alert_networkErrorMessage: "Не вдалося підключитися до сервера.",
};