export default {
    username: 'Користувач',
    password: 'Пароль',
    login: 'Увійти',
    welcome: 'Ласкаво просимо',
    change_language: 'Змінити мову',
    Tabs: 'Головна',

    Lista_instalaciones: 'Установки',
    Maintenance: 'Технічне обслуговування',
    DetallesInstalacion: 'Деталі установки',
    Grabar: 'Зберегти',
    EstadoStore: 'Стан store',
    Nodata: 'Немає даних',
    DosimacRegistration: 'Реєстрація',
    NewDmMaternity: 'Новий Dosimac (пологи)',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Оновлення Dosimac (пологи)',
    NewDmGestation: 'Новий Dosimac (вагітність)',
    UpdDmGestation: 'Оновлення Dosimac (вагітність)',
    StartScan: 'Пошук пристроїв DOSIMAC',
    DosimacList: 'Пристрої DOSIMAC',
    PressToScan: 'Натисніть',
    DosimacSetup: 'Конфігурація',
    TestoPresioneAlta: 'Натисніть кнопку, щоб шукати пристрої',
    Instalación_seleccionada: 'Вибрана установка',
    NoInstalacionSeleccionada: 'Установка не вибрана',
    BorrarGranja: 'Видалити ферму',
    Deseaborrarlagranja: 'Бажаєте видалити ферму?',
    Guardar: 'Зберегти',
    Cancelar: 'Скасувати',
    Aceptar: 'Прийняти',
    NombreGranja: 'Назва ферми',
    Localidad: 'Місцезнаходження',
    Provincia: 'Область',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Пароль Wifi',
    No_hay_dispositivos: 'Немає пристроїв',
    Aviso: 'Повідомлення',
    SearchingDevices: 'Пошук пристроїв...',
    NoSePuedeBorrarGranja: 'Неможливо видалити нову ферму',
    settings: 'Налаштування',
    softwareVersion: 'Версія програмного забезпечення',
    numeroCoral: 'Номер загону',
    numeroMaquina: 'Номер машини',
    Enviar: 'Надіслати',
    Salir: 'Вийти',
    Informacion: 'Інформація',

    InicioConfiguracion: "Запуск підключення",
    ConfiguracionWifi: "Налаштування...",
    ConfiguracionRealizada: "*Налаштування завершено*",
    ErrorConfiguracion: "*Помилка налаштування*",
    CapturaTagCorral: "Зчитати тег загону",
    CorralTag: "Тег загону",
    versionUint16: "Ця версія пристрою підтримує загони лише до 65000",
    versionUint32: "Ця версія пристрою підтримує загони до 4000000000",
    EnvioConfiguracion: "Надсилання конфігурації",
    NumeroCorral: "Номер загону",
    NumeroMaquina: "Номер машини",
    Corralnovalido: 'Невірний загін',
    Númeromáquinanovalido: 'Невірний номер машини',
};