
export default {
    username: 'Utilisateur',
    password: 'Mot de passe',
    login: 'Connexion',
    welcome: 'Bienvenue',
    change_language: 'Changer de langue',
    Tabs: 'Accueil',

    Lista_instalaciones: 'Installations',
    Maintenance: 'Maintenance',
    DetallesInstalacion: 'Détails installation',
    Grabar: 'Enregistrer',
    EstadoStore: 'État store',
    Nodata: 'Pas de données',
    DosimacRegistration: 'Inscription',
    NewDmMaternity: 'Nouveau Dosimac maternité',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: 'Changement Dosimac maternité',
    NewDmGestation: 'Nouveau Dosimac gestation',
    UpdDmGestation: 'Changement Dosimac gestation',
    StartScan: 'Chercher appareils DOSIMAC',
    DosimacList: 'Appareils DOSIMAC',
    PressToScan: 'Appuyez',
    DosimacSetup: 'Configuration',
    TestoPresioneAlta: 'Appuyez sur le bouton pour rechercher des appareils',
    Instalación_seleccionada: 'Installation sélectionnée',
    NoInstalacionSeleccionada: 'Aucune installation sélectionnée',
    BorrarGranja: 'Supprimer la ferme',
    Deseaborrarlagranja: 'Voulez-vous supprimer la ferme ?',
    Guardar: 'Enregistrer',
    Cancelar: 'Annuler',
    Aceptar: 'Accepter',
    NombreGranja: 'Nom de la ferme',
    Localidad: 'Localité',
    Provincia: 'Province',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Mot de passe Wifi',
    No_hay_dispositivos: 'Aucun appareil',
    Aviso: 'Avis',
    SearchingDevices: 'Recherche des appareils...',
    NoSePuedeBorrarGranja: 'Impossible de supprimer une nouvelle ferme',
    settings: 'Paramètres',
    softwareVersion: 'Version du logiciel',
    numeroCoral: "Numéro d’enclos",
    numeroMaquina: 'Numéro de machine',
    Enviar: 'Envoyer',
    Salir: 'Quitter',
    Informacion: 'Information',

    InicioConfiguracion: "Démarrage de la connexion",
    ConfiguracionWifi: "Configuration en cours...",
    ConfiguracionRealizada: "*Configuration terminée*",
    ErrorConfiguracion: "*Erreur de configuration*",
    CapturaTagCorral: "Capturer le tag de l’enclos",
    CorralTag: "Tag de l’enclos",
    versionUint16: "Cette version de l’appareil ne prend en charge que des enclos jusqu’à 65000",
    versionUint32: "Cette version de l’appareil prend en charge des enclos jusqu’à 4000000000",
    EnvioConfiguracion: "Envoi de la configuration",
    NumeroCorral: "Numéro d’enclos",
    NumeroMaquina: "Numéro de machine",
    Corralnovalido: "Enclos non valide",
    Númeromáquinanovalido: "Numéro de machine non valide",

    gestacionConfig_screenTitle: "Configuration Gestation",
    gestacionConfig_chooseOptionTitle: "Choisissez une option",
    gestacionConfig_chooseOptionDescription: "Définissez le flux avant de commencer avec le lecteur.",

    gestacionConfig_entry: "Entrée",
    gestacionConfig_exit: "Sortie",
    gestacionConfig_reading: "Lecture",
    gestacionConfig_search: "Recherche",

    gestacionConfig_entryParamsTitle: "Paramètres d'entrée",
    gestacionConfig_exitParamsTitle: "Paramètres de sortie",
    gestacionConfig_entryParamsDescription: "Sélectionnez le corral et le comportement du flux.",
    gestacionConfig_exitParamsDescription: "Configurez le comportement du flux de sortie.",

    gestacionConfig_corralLabel: "Corral",
    gestacionConfig_corralPlaceholder: "Ex : 1",
    gestacionConfig_corralRequired: "Saisissez le corral pour continuer.",

    gestacionConfig_detectUnknownTitle: "Identifier les animaux inconnus",
    gestacionConfig_detectUnknownDescription: "Lorsque vous lirez un animal non identifié, vous pourrez lui attribuer un ID",

    gestacionConfig_confirmTitle: "Confirmer l'envoi",
    gestacionConfig_confirmDescription: "Une confirmation sera demandée avant l'envoi des enregistrements.",

    gestacionConfig_animalSearchTitle: "Recherche d'animal",
    gestacionConfig_animalSearchDescription: "Choisissez si vous souhaitez rechercher par crotal ou par ID.",
    gestacionConfig_searchByCrotal: "Par crotal",
    gestacionConfig_searchById: "Par ID",
    gestacionConfig_manual: "Manuel",
    gestacionConfig_withSword: "Avec épée",

    gestacionConfig_crotalLabelSearch: "Crotal",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "Ex : 982091072397436",
    gestacionConfig_idPlaceholderSearch: "Ex : A13",
    gestacionConfig_crotalRequiredSearch: "Saisissez un crotal pour continuer.",
    gestacionConfig_idRequiredSearch: "Saisissez un ID pour continuer.",

    gestacionConfig_searchWithSwordHelp: "En continuant, l'épée sera lue sur cet écran et l'animal sera recherché avec ce crotal.",

    gestacionConfig_readingSword: "Lecture de l'épée...",
    gestacionConfig_waitingMatch: "En attente de correspondance",
    gestacionConfig_searchingAnimal: "Recherche de l'animal...",

    gestacionConfig_readingSwordDescription: "Approchez le crotal du lecteur pour identifier l'animal.",
    gestacionConfig_waitingMatchDescription: "Animal localisé. Approchez maintenant à l'épée le crotal {{crotal}} pour confirmer la correspondance.",
    gestacionConfig_searchingAnimalDescription: "Consultation des informations de l'animal dans le backend.",

    gestacionConfig_awrDisconnectedTitle: "AWR non connecté",
    gestacionConfig_awrSavedDescription: "Vous avez des épées enregistrées. Appuyez pour en sélectionner une.",
    gestacionConfig_awrNotSavedDescription: "Vous n'avez aucune épée enregistrée. Appuyez pour en scanner une.",

    gestacionConfig_scan: "Scanner",
    gestacionConfig_continue: "Continuer",

    gestacionConfig_alerts_error: "Erreur",
    gestacionConfig_alerts_networkError: "Erreur réseau",
    gestacionConfig_alerts_networkErrorMessage: "Impossible de se connecter au serveur.",
    gestacionConfig_alerts_backendNoValidCrotal: "Le backend n'a pas renvoyé un crotal valide pour la comparaison.",
    gestacionConfig_alerts_awrNotConnected: "AWR non connecté",
    gestacionConfig_alerts_connectSwordBeforeContinue: "Connectez une épée avant de continuer.",
    gestacionConfig_alerts_couldNotStartReading: "Impossible de démarrer la lecture avec l'épée.",

    gestacionConfig_alerts_missingData: "Donnée manquante",
    gestacionConfig_alerts_writeCrotalToSearch: "Saisissez un crotal pour rechercher.",
    gestacionConfig_alerts_writeIdToSearch: "Saisissez un ID pour rechercher.",

    gestacionConfig_alerts_notFound: "Introuvable",
    gestacionConfig_alerts_animalNotFoundByCrotal: "Aucun animal n'existe avec ce crotal.",
    gestacionConfig_alerts_animalNotFoundById: "Aucun animal n'existe avec cet ID.",

    gestacionConfig_alerts_warning: "Avertissement",
    gestacionConfig_alerts_searchError: "Erreur de recherche",


    maternidadConfig_screenTitle: "Configuration Maternité",
    maternidadConfig_chooseOptionTitle: "Choisissez une option",
    maternidadConfig_chooseOptionDescription: "Définissez le flux avant de commencer avec le lecteur.",
    maternidadConfig_entry: "Entrée",
    maternidadConfig_exit: "Sortie",
    maternidadConfig_reading: "Lecture",
    maternidadConfig_search: "Recherche",
    maternidadConfig_entryParamsTitle: "Paramètres d'entrée",
    maternidadConfig_exitParamsTitle: "Paramètres de sortie",
    maternidadConfig_entryParamsDescription: "Sélectionnez le corral et le comportement du flux.",
    maternidadConfig_exitParamsDescription: "Configurez le comportement du flux de sortie.",
    maternidadConfig_corralLabel: "Corral",
    maternidadConfig_corralPlaceholder: "Ex : 1",
    maternidadConfig_corralRequired: "Saisissez le corral pour continuer.",
    maternidadConfig_detectUnknownTitle: "Identifier les animaux inconnus",
    maternidadConfig_detectUnknownDescription: "Lorsque vous lirez un animal non identifié, vous pourrez lui attribuer un ID",
    maternidadConfig_confirmTitle: "Confirmer l'envoi",
    maternidadConfig_confirmDescription: "Une confirmation sera demandée avant l'envoi de chaque enregistrement.",
    maternidadConfig_animalSearchTitle: "Recherche d'animal",
    maternidadConfig_animalSearchDescription: "Choisissez si vous voulez rechercher par crotal ou par ID.",
    maternidadConfig_searchByCrotal: "Par crotal",
    maternidadConfig_searchById: "Par ID",
    maternidadConfig_manual: "Manuel",
    maternidadConfig_withSword: "Avec baguette",
    maternidadConfig_crotalLabelSearch: "Crotal",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "Ex : 982091072397436",
    maternidadConfig_idPlaceholderSearch: "Ex : A13",
    maternidadConfig_crotalRequiredSearch: "Saisissez un crotal pour continuer.",
    maternidadConfig_idRequiredSearch: "Saisissez un ID pour continuer.",
    maternidadConfig_searchWithSwordHelp: "En appuyant sur Scanner, la baguette sera lue sur cet écran et l'animal sera recherché avec ce crotal.",
    maternidadConfig_readingSword: "Lecture de la baguette...",
    maternidadConfig_waitingMatch: "En attente de correspondance",
    maternidadConfig_searchingAnimal: "Recherche de l'animal...",
    maternidadConfig_readingSwordDescription: "Approchez le crotal du lecteur pour identifier l'animal.",
    maternidadConfig_waitingMatchDescription: "Animal localisé. Approchez maintenant le crotal {{crotal}} de la baguette pour confirmer la correspondance.",
    maternidadConfig_searchingAnimalDescription: "Consultation des informations de l'animal dans le backend.",
    maternidadConfig_awrDisconnectedTitle: "AWR non connecté",
    maternidadConfig_awrSavedDescription: "Vous avez des AWR enregistrés. Appuyez pour en sélectionner un.",
    maternidadConfig_awrNotSavedDescription: "Vous n'avez aucun AWR enregistré. Appuyez pour en scanner un.",
    maternidadConfig_scan: "Scanner",
    maternidadConfig_continue: "Continuer",
    maternidadConfig_alert_error: "Erreur",
    maternidadConfig_alert_invalidBackendCrotal: "Le backend n'a pas renvoyé un crotal valide pour la comparaison.",
    maternidadConfig_alert_awrNotConnected: "AWR non connecté",
    maternidadConfig_alert_connectSwordBeforeContinue: "Connectez une baguette avant de continuer.",
    maternidadConfig_alert_couldNotStartReading: "Impossible de démarrer la lecture avec la baguette.",
    maternidadConfig_alert_missingData: "Donnée manquante",
    maternidadConfig_alert_writeCrotalToSearch: "Saisissez un crotal pour rechercher.",
    maternidadConfig_alert_writeIdToSearch: "Saisissez un ID pour rechercher.",
    maternidadConfig_alert_notFound: "Introuvable",
    maternidadConfig_alert_noAnimalWithCrotal: "Aucun animal n'existe avec ce crotal.",
    maternidadConfig_alert_noAnimalWithId: "Aucun animal n'existe avec cet ID.",
    maternidadConfig_alert_warning: "Avis",
    maternidadConfig_alert_searchError: "Erreur de recherche",
    maternidadConfig_alert_networkError: "Erreur réseau",
    maternidadConfig_alert_networkErrorMessage: "Impossible de se connecter au serveur.",
};