export default {
    username: '用戶名',
    password: '密碼',
    login: '登入',
    welcome: '歡迎',
    change_language: '切換語言',
    Tabs: '首頁',

    Lista_instalaciones: '安裝',
    Maintenance: '維護',
    DetallesInstalacion: '安裝詳情',
    Grabar: '保存',
    EstadoStore: '存儲狀態',
    Nodata: '沒有數據',
    DosimacRegistration: ' 註冊',
    NewDmMaternity: '新 Dosimac 產房',
    DosimacG: 'Dosimac-G',
    DosimacI: 'Dosimac-I',
    UpdDmMaternity: '更新 Dosimac 產房',
    NewDmGestation: '新 Dosimac 妊娠',
    UpdDmGestation: '更新 Dosimac 妊娠',
    StartScan: '搜尋 DOSIMAC 裝置',
    DosimacList: 'DOSIMAC 裝置',
    PressToScan: '按一下',
    DosimacSetup: '設定',
    TestoPresioneAlta: '按下按鈕以搜尋裝置',
    Instalación_seleccionada: '已選擇的安裝',
    NoInstalacionSeleccionada: '未選擇安裝',
    BorrarGranja: '刪除農場',
    Deseaborrarlagranja: '確定要刪除農場嗎？',
    Guardar: '保存',
    Cancelar: '取消',
    Aceptar: '接受',
    NombreGranja: '農場名稱',
    Localidad: '地點',
    Provincia: '省份',
    NombreWifi: 'Wifi SSID',
    PasswordWifi: 'Wifi 密碼',
    No_hay_dispositivos: '沒有裝置',
    Aviso: '通知',
    SearchingDevices: '正在搜尋裝置...',
    NoSePuedeBorrarGranja: '無法刪除新的農場',
    settings: '設定',
    softwareVersion: '軟體版本',
    numeroCoral: '畜欄編號',
    numeroMaquina: '機器編號',
    Enviar: '送出',
    Salir: '離開',
    Informacion: '資訊',

    InicioConfiguracion: "開始連線",
    ConfiguracionWifi: "正在設定…",
    ConfiguracionRealizada: "*設定完成*",
    ErrorConfiguracion: "*設定錯誤*",
    CapturaTagCorral: "擷取畜欄標籤",
    CorralTag: "畜欄標籤",
    versionUint16: "此裝置版本僅支援畜欄編號至 65000",
    versionUint32: "此裝置版本支援畜欄編號至 4000000000",
    EnvioConfiguracion: "正在傳送設定",
    NumeroCorral: "畜欄編號",
    NumeroMaquina: "機器編號",
    Corralnovalido: '無效的畜欄',
    Númeromáquinanovalido: '無效的機器編號',
    configuarIntalacion: "請設定安裝以繼續",

    gestacionConfig_screenTitle: "妊娠設定",
    gestacionConfig_chooseOptionTitle: "選擇一個選項",
    gestacionConfig_chooseOptionDescription: "在開始使用讀取器之前，先定義流程。",

    gestacionConfig_entry: "進入",
    gestacionConfig_exit: "離開",
    gestacionConfig_reading: "讀取",
    gestacionConfig_search: "搜尋",

    gestacionConfig_entryParamsTitle: "進入參數",
    gestacionConfig_exitParamsTitle: "離開參數",
    gestacionConfig_entryParamsDescription: "選擇欄位與流程行為。",
    gestacionConfig_exitParamsDescription: "設定離開流程的行為。",

    gestacionConfig_corralLabel: "欄位",
    gestacionConfig_corralPlaceholder: "例：1",
    gestacionConfig_corralRequired: "請輸入欄位以繼續。",

    gestacionConfig_detectUnknownTitle: "識別未知動物",
    gestacionConfig_detectUnknownDescription: "當你讀取到未識別的動物時，可以為牠指定一個 ID",

    gestacionConfig_confirmTitle: "確認送出",
    gestacionConfig_confirmDescription: "送出紀錄前會要求確認。",

    gestacionConfig_animalSearchTitle: "動物搜尋",
    gestacionConfig_animalSearchDescription: "選擇要用耳標還是 ID 搜尋。",
    gestacionConfig_searchByCrotal: "依耳標",
    gestacionConfig_searchById: "依 ID",
    gestacionConfig_manual: "手動",
    gestacionConfig_withSword: "使用讀取器",

    gestacionConfig_crotalLabelSearch: "耳標",
    gestacionConfig_idLabelSearch: "ID",
    gestacionConfig_crotalPlaceholderSearch: "例：982091072397436",
    gestacionConfig_idPlaceholderSearch: "例：A13",
    gestacionConfig_crotalRequiredSearch: "請輸入耳標以繼續。",
    gestacionConfig_idRequiredSearch: "請輸入 ID 以繼續。",

    gestacionConfig_searchWithSwordHelp: "繼續後，會在此畫面使用讀取器讀取，並以該耳標搜尋動物。",

    gestacionConfig_readingSword: "正在讀取讀取器...",
    gestacionConfig_waitingMatch: "等待比對",
    gestacionConfig_searchingAnimal: "正在搜尋動物...",

    gestacionConfig_readingSwordDescription: "請將耳標靠近讀取器以識別動物。",
    gestacionConfig_waitingMatchDescription: "已找到動物。現在請將耳標 {{crotal}} 靠近讀取器以確認比對。",
    gestacionConfig_searchingAnimalDescription: "正在後端查詢動物資訊。",

    gestacionConfig_awrDisconnectedTitle: "AWR 未連線",
    gestacionConfig_awrSavedDescription: "你有已儲存的讀取器。點擊以選擇一個。",
    gestacionConfig_awrNotSavedDescription: "你沒有已儲存的讀取器。點擊以掃描一個。",

    gestacionConfig_scan: "掃描",
    gestacionConfig_continue: "繼續",

    gestacionConfig_alerts_error: "錯誤",
    gestacionConfig_alerts_networkError: "網路錯誤",
    gestacionConfig_alerts_networkErrorMessage: "無法連線到伺服器。",
    gestacionConfig_alerts_backendNoValidCrotal: "後端沒有回傳可供比對的有效耳標。",
    gestacionConfig_alerts_awrNotConnected: "AWR 未連線",
    gestacionConfig_alerts_connectSwordBeforeContinue: "請先連接讀取器再繼續。",
    gestacionConfig_alerts_couldNotStartReading: "無法使用讀取器開始讀取。",

    gestacionConfig_alerts_missingData: "缺少資料",
    gestacionConfig_alerts_writeCrotalToSearch: "請輸入耳標以搜尋。",
    gestacionConfig_alerts_writeIdToSearch: "請輸入 ID 以搜尋。",

    gestacionConfig_alerts_notFound: "找不到",
    gestacionConfig_alerts_animalNotFoundByCrotal: "找不到具有該耳標的動物。",
    gestacionConfig_alerts_animalNotFoundById: "找不到具有該 ID 的動物。",

    gestacionConfig_alerts_warning: "提醒",
    gestacionConfig_alerts_searchError: "搜尋錯誤",

    maternidadConfig_screenTitle: "分娩設定",
    maternidadConfig_chooseOptionTitle: "選擇一個選項",
    maternidadConfig_chooseOptionDescription: "開始使用讀取器之前，請先定義流程。",
    maternidadConfig_entry: "進入",
    maternidadConfig_exit: "離開",
    maternidadConfig_reading: "讀取",
    maternidadConfig_search: "搜尋",
    maternidadConfig_entryParamsTitle: "進入參數",
    maternidadConfig_exitParamsTitle: "離開參數",
    maternidadConfig_entryParamsDescription: "選擇欄位與流程行為。",
    maternidadConfig_exitParamsDescription: "設定離開流程的行為。",
    maternidadConfig_corralLabel: "欄位",
    maternidadConfig_corralPlaceholder: "例如：1",
    maternidadConfig_corralRequired: "請輸入欄位以繼續。",
    maternidadConfig_detectUnknownTitle: "識別未知動物",
    maternidadConfig_detectUnknownDescription: "當你讀取到未識別的動物時，可以為它指定一個 ID",
    maternidadConfig_confirmTitle: "確認送出",
    maternidadConfig_confirmDescription: "在送出每筆記錄前會要求確認。",
    maternidadConfig_animalSearchTitle: "動物搜尋",
    maternidadConfig_animalSearchDescription: "選擇要以耳標或 ID 搜尋。",
    maternidadConfig_searchByCrotal: "依耳標",
    maternidadConfig_searchById: "依 ID",
    maternidadConfig_manual: "手動",
    maternidadConfig_withSword: "用讀取器",
    maternidadConfig_crotalLabelSearch: "耳標",
    maternidadConfig_idLabelSearch: "ID",
    maternidadConfig_crotalPlaceholderSearch: "例如：982091072397436",
    maternidadConfig_idPlaceholderSearch: "例如：A13",
    maternidadConfig_crotalRequiredSearch: "請輸入耳標以繼續。",
    maternidadConfig_idRequiredSearch: "請輸入 ID 以繼續。",
    maternidadConfig_searchWithSwordHelp: "按下掃描後，系統會在此畫面讀取讀取器，並用該耳標搜尋動物。",
    maternidadConfig_readingSword: "正在讀取讀取器...",
    maternidadConfig_waitingMatch: "等待比對",
    maternidadConfig_searchingAnimal: "正在搜尋動物...",
    maternidadConfig_readingSwordDescription: "請將耳標靠近讀取器以識別動物。",
    maternidadConfig_waitingMatchDescription: "已找到動物。現在請將耳標 {{crotal}} 靠近讀取器以確認比對。",
    maternidadConfig_searchingAnimalDescription: "正在從後端查詢動物資訊。",
    maternidadConfig_awrDisconnectedTitle: "AWR 未連線",
    maternidadConfig_awrSavedDescription: "你有已儲存的 AWR。點擊以選擇一個。",
    maternidadConfig_awrNotSavedDescription: "你沒有任何已儲存的 AWR。點擊以掃描一個。",
    maternidadConfig_scan: "掃描",
    maternidadConfig_continue: "繼續",
    maternidadConfig_alert_error: "錯誤",
    maternidadConfig_alert_invalidBackendCrotal: "後端未回傳可用於比對的有效耳標。",
    maternidadConfig_alert_awrNotConnected: "AWR 未連線",
    maternidadConfig_alert_connectSwordBeforeContinue: "請先連接讀取器再繼續。",
    maternidadConfig_alert_couldNotStartReading: "無法使用讀取器開始讀取。",
    maternidadConfig_alert_missingData: "缺少資料",
    maternidadConfig_alert_writeCrotalToSearch: "請輸入耳標以搜尋。",
    maternidadConfig_alert_writeIdToSearch: "請輸入 ID 以搜尋。",
    maternidadConfig_alert_notFound: "找不到",
    maternidadConfig_alert_noAnimalWithCrotal: "找不到具有該耳標的動物。",
    maternidadConfig_alert_noAnimalWithId: "找不到具有該 ID 的動物。",
    maternidadConfig_alert_warning: "警告",
    maternidadConfig_alert_searchError: "搜尋錯誤",
    maternidadConfig_alert_networkError: "網路錯誤",
    maternidadConfig_alert_networkErrorMessage: "無法連接到伺服器。",
};